docs/vtex-io/Store Framework Apps/basic-components/vtex-product-customizer.md
=> adding missing <\img> tag on vtex-product-customizer.md

docs/vtex-io/Store Framework Apps/basic-components/vtex-product-specifications.md
=> adding missing <\img> tag on vtex-product-specifications.md

docs/vtex-io/Store Framework Apps/advanced-components/vtex-category-menu.md
=> adding missing <\img> tag on vtex-category-menu.md

docs/vtex-io/Store Framework Apps/basic-components/vtex-product-summary.md
=> adding missing <\img> tag on vtex-product-summary.md

docs/guides/Buyer Organizations/buyer-organizations-api-overview.md
This PR moves the Buyer Organizations API overview.md file that was previously in the [/readme-api-md](https://github.com/vtexdocs/dev-portal-content/tree/main/readme-api-md) folder, to a new folder in [/docs/guides](https://github.com/vtexdocs/dev-portal-content/tree/main/docs/guides).
=> Move Buyer Organizations API overview

docs/vtex-io/Store Framework Apps/layout-apps/vtex-tab-layout.md
I added a quotation mark at the close of the tab-layout declaration.
=> fix: ⚒️ fix the tab-layout block declaration

docs/guides/Integration Guides/pii-platform-version/profile-system.md
I changed the parameter name and related text from `alternateKey` to the correct name: `alternativeKey`.
=> Correcting parameter name

docs/guides/Integration-Guides/catalog-integration.md
Fixed broken link to catalog API. Also, there's another broken link for  the google-import app details in the same page, but I didn't find a valid resource for that one.
=> Fixed broken link

docs/vtex-io/Store-Framework-Apps/pixel-apps/setting-up-lazy-load-for-pixel-apps.md
I was reading this page when I noticed the variable `isLazyLoad` wasn't defined anywhere, and it made sense for it to be the existing `experimentalLazyLoad` defined above.
Also noticed this `:warning` and tried to fix it.
=> fix(pixel-apps): Fix a variable in the code example

docs/vtex-io/Store-Framework-Apps/basic-components/vtex-product-summary-productsummarylist.md
Looks like our Markdown renderer doesn't like new lines:
https://developers.vtex.com/docs/guides/vtex-product-summary-productsummarylist
=> Fixed empty callout

docs/guides/Infrastructure/store-availability/how-to-load-test-a-store.md
For some reason, hash links in this article were missing:
https://developers.vtex.com/docs/guides/how-to-load-test-a-store
I added them :-)
=> Added missing hash links

docs/guides/Getting-Started/catalog-overview.md
Replacing current catalog overview article, with previous html from [this point in history](https://github.com/vtexdocs/dev-portal-content/blob/46d716d00292da27b15ed807c324825c3509a306/docs/guides/Getting-Started/catalog-overview.md), to correct bugged HTML render.
=> replacing bugged article with old version

docs/guides/Checkout/configuration-section-api-quick-start-guides/clear-orderform-message-field-from-cart.md
Fix clear-orderform-message-field-from-cart.md
It relates to [LOC-10427](https://vtex-dev.atlassian.net/browse/LOC-10427) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit))
[LOC-10427]: https://vtex-dev.atlassian.net/browse/LOC-10427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on clear-orderform-message-field-from-cart.md

docs/vtex-io/Storefront-Guides/google-tag-manager.md
Hide Migrating GTM doc
With the new GTM app version, the doc for Migrating GTM is no longer valid. This PR deletes its mention on the main doc.
=> Update GTM: Hiding Migrating doc

docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-managing-application-logs.md
I noticed while browsing this documentation that the order of the TypeScript variable name and its type was inverted.
=> Fix TypeScript variable & type order in the examples

docs/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-building-a-carousel-using-slider-layout.md
It relates to task [LOC-10593](https://vtex-dev.atlassian.net/browse/LOC-10593) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10593]: https://vtex-dev.atlassian.net/browse/LOC-10593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-building-a-carousel-using-slider-layout.md

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-installing-google-tag-manager.md
This PR fixes:
- Deletes the duplicated paragraph about the GTM Blocklist feature.
- Deletes `Step 1: Installing the Google Tag Manager in Admin` name.
- Add `step 8` in `Step by step`.
=> Fix: Installing GTM

docs/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-building-a-product-details-page.md
It relates to task [LOC-10615](https://vtex-dev.atlassian.net/browse/LOC-10615) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10615]: https://vtex-dev.atlassian.net/browse/LOC-10615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-building-a-product-details-page.md

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-installing-google-tag-manager.md
Deleted the mention of `Step 2` since it no longer exists in the doc.
=> Fix: Deleted `step 2` in the GTM installation process

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
https://developers.vtex.com/docs/guides/vtex-io-documentation-setting-up-google-tag-manager
Better organize the table of supported events to clarify which events are fully supported and which are not.
We decided to also add a new section to describe the changes we make to the GTM Container Template.
Before|After
-|-
=> Better organize the list of GTM/GA4 supported events

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developnativeintegrationswithpixelapps/vtex-io-documentation-4-configuringyourappsettings.md
It relates to task [LOC-10748](https://vtex-dev.atlassian.net/browse/LOC-10748) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10748]: https://vtex-dev.atlassian.net/browse/LOC-10748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on a vtex-io-documentation file

docs/vtex-io/Perks/best-practices/vtex-io-documentation-developing-custom-storefront-components.md
It relates to task [LOC-10841](https://vtex-dev.atlassian.net/browse/LOC-10841) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10841]: https://vtex-dev.atlassian.net/browse/LOC-10841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-developing-custom-storefront-components.md

docs/vtex-io/Reference/vtex-io-documentation-vtex-io-cli-installation-and-command-reference/vtex-io-documentation-vtex-io-cli-usage.md
It relates to task [LOC-10753](https://vtex-dev.atlassian.net/browse/LOC-10753) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10753]: https://vtex-dev.atlassian.net/browse/LOC-10753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-vtex-io-cli-usage.md

docs/guides/Master-Data/getting-started-1/starting-to-work-on-master-data-with-json-schema.md, docs/vtex-io/App-Guides/create-master-data-crud-app.md
Adding warnings about the limit of 60 schemas per data entity to two guides.
=> Master data v2 schema limit

docs/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-3-settingyourstoretheme.md, docs/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-4-declaring-a-theme-block.md
It relates to task [LOC-11451](https://vtex-dev.atlassian.net/browse/LOC-11451) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-11451]: https://vtex-dev.atlassian.net/browse/LOC-11451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-4-declaring-a-theme-block.md

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developnativeintegrationswithpixelapps/vtex-io-documentation-5-writingtheheaderandbodyscripts.md
It relates to task [LOC-10770](https://vtex-dev.atlassian.net/browse/LOC-10770) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10770]: https://vtex-dev.atlassian.net/browse/LOC-10770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-5-writingtheheaderandbodyscripts.md

docs/vtex-io/Reference/vtex-io-documentation-vtex-io-cli-installation-and-command-reference/vtex-io-documentation-vtex-io-cli-command-reference.md
It relates to task [LOC-10518](https://vtex-dev.atlassian.net/browse/LOC-10518) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10518]: https://vtex-dev.atlassian.net/browse/LOC-10518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-vtex-io-cli-command-reference.md

docs/vtex-io/App-Guides/ab-tests/vtex-io-documentation-performing-ab-testing-between-legacy-and-io.md
https://developers.vtex.com/docs/guides/vtex-io-documentation-performing-ab-testing-between-legacy-and-io
I found some typos in this documentation while browsing it:
1. When `vtex use {workspace}` was demonstrated, the callout used an example for `vtex login`. I think we mean to give an example for `vtex use`.
2. Workspace names must all be lowercase, so `vtex use Master` should be `vtex use master`.
3. Remove an extra `@` in `vtex.colossus-legacy-proxy@@1.8.9-hkignore`. Not sure if it works with double `@`s, but normally only 1 is required.
=> Fix some typos in the "A/B testing Legacy and IO store versions" guide

README.md
This PR adds a new topic in the README.md on how to add release notes updates in the Developer Portal homepage
P.s.: I removed the link to the `vtex/education-tools` repository because it was failing the checks, probably because it's a private repo:
=> Add: How to update the `Last Updates` section in the portal's homepage.

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-app.md
PR created to add a callout to the Payment App Dev Guide (EDU-10704).
=> Add callout Payment App Dev Guide

docs/guides/Orders/order-canceling-improvements-beta.md
The feature is no longer in Beta, and there is a new documentation published in Help Center that was linked.
=> Remove beta mention form cancel order

docs/guides/Master-Data/master-data-how-it-works/vtable.md
=> Add warning that VTable is deprecated

docs/guides/Getting-Started/orders-overview.md
Changed callout about data retention.
There was another change in the data retention policy for retrieving orders from more than 2 years ago. Now, it is no longer possible to open a ticket for support for data requests, because VTEX doesn't store that information anymore. In those endpoints, there was the same callout about this, and I have removed a sentence that said it was possible to open a ticket.
=> update orders overview callout about data retention

docs/release-notes/2024-03-07-faststore-content-in-the-developer-portal.md
This PR fixes the URLs to the FastStore portal mentioned in [the release note about content migration](https://developers.vtex.com/updates/release-notes/2024-03-07-faststore-content-in-the-developer-portal).
=> Fix: FastStore release note URL

docs/faststore/docs/customization/using-themes/overview.mdx, docs/faststore/docs/reference/project-structure/overview.mdx, docs/faststore/docs/what-is-faststore.mdx
Improve the description of FS packages, fix the introductory part mentioning FS packages, and fix the namespacing in the themes docs. Related to the following feedback:
- [EDU-11745](https://vtex-dev.atlassian.net/browse/EDU-11745)
- [EDU-11696](https://vtex-dev.atlassian.net/browse/EDU-11696)
[EDU-11745]: https://vtex-dev.atlassian.net/browse/EDU-11745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-11696]: https://vtex-dev.atlassian.net/browse/EDU-11696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: FastStore docs quick wins

docs/faststore/docs/headless-cms/3-adding-content-types-and-sections.mdx, docs/faststore/docs/headless-cms/widgets.mdx
Migrating the Widgets documentation from FastStore v1 to FastStore v2
Updating navigation.json: https://github.com/vtexdocs/devportal/pull/610
=> Chore: Migrating Headless CMS

docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx, docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
- Relates to #1111 
- `navigation.json` updated: [PR 646](https://github.com/vtexdocs/devportal/pull/646) 
- Jira task: [EDU-11286](https://vtex-dev.atlassian.net/browse/EDU-11286) 
[EDU-11286]: https://vtex-dev.atlassian.net/browse/EDU-11286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-11286: Section override (Part II - Unedited files)

docs/guides/Integration-Guides/api-guides/setting-up-dkim-for-transactional-emails.md
The documentation was wrongly instructing to add TXT record to validate the DKIM. Instead the customer should add CNAME records in their DNS records manager.
=> FIX: setting-up-dkim-for-transactional-emails.md

docs/faststore/docs/headless-cms/multiple-page-template.mdx
This PR aims to adjust some multiple-page template instructions for PDPs and add a note regarding the precedence of PDP slugs with SKU ID.
FastStore PR 
- https://github.com/vtex/faststore/pull/2321
=> feat: adds instructions to PDP slugs with sku id

docs/faststore/components/features/auth-content.mdx, docs/faststore/components/features/overview.mdx
This PR adds the documentation about the Auth Content feature. It relates to the new initiative FastStore B2B. To learn more about this initiative, you can access the [Product Vision documentation](https://docs.google.com/document/d/17tJprtQEs9izw6Zh49thA90NuljoFLoMOyHwJvJAH1Q).
- PR editing the dev portal sidebar: https://github.com/vtexdocs/devportal/pull/660
- The feature PR is merged https://github.com/vtex/faststore/pull/2282
[Feat: Add Auth Content feature #2282 Merged](https://github.com/vtex/faststore/pull/2282)
[Auth Content documentation](https://developers.vtex.com/docs/guides/faststore/features-auth-content)
[B2B Faststore Product Vision](https://docs.google.com/document/d/17tJprtQEs9izw6Zh49thA90NuljoFLoMOyHwJvJAH1Q/edit#heading=h.tglo77yl0lf)
[B2B Faststore …
=> FastStore: Auth content acces

docs/guides/Checkout/security.md
Changing the slug of a Checkout subcategory because we need the `security` slug for the Security guide that is part of 24H1KR3 (https://github.com/vtexdocs/dev-portal-content/pull/1169).
Related to https://github.com/vtexdocs/devportal/pull/666, where I adjusted navigation accordingly.
=> update checkout security guide url

docs/faststore/docs/go-live/2-configuring-external-dns.mdx
To follow up on #inc-844, the documentation suggests only adding the hostname (without "www") to the list. This can confuse users, as the store actually operates using the "www" subdomain.
This PR updates the documentation to clarify that both "www" and non-" "www" versions of the hostname should be added.
=> Incident-844: Update 2-configuring-external-dns.mdx

docs/release-notes/2024-06-10-site-editor-content-storage-updated.md
Following up on [this thread](https://vtex.slack.com/archives/C031K7X87NG/p1717773945428649?thread_ts=1717611993.024289&cid=C031K7X87NG), and aligning with James and Camila, we will publish a release note hidden on the dev portal. This is because only one customer from a native English-speaking country will have access to the site editor content storage improvements on June 10th. By the beginning of next week, after we have the translations for Portuguese and Spanish, we will publish the final version of this announcement in the help center portal.
To access the release note:
1. Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-12666-site-editor) to set up the portal with this branch changes.
2. In the same browser tab, copy and paste the following link to access the …
=> EDU-12666 New release note: Site Editor

docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx
The FastStore WebOps current state has a bug regarding the Headless CMS publishing process, which stores that set the `Build Webhook URL` field will cause timeout errors on the Releases-side. We should remove this info `temporarily` to avoid those situations while we are working in the Integrations API.
=> chore: Remove temporarily `Build Webhook URL` info

docs/faststore/docs/customization/building-sections/override-use-cases/adding-an-image-to-the-alert-component.mdx, docs/faststore/docs/customization/building-sections/override-use-cases/adding-more-icon-options-to-the-alert-component.mdx, docs/faststore/docs/customization/building-sections/override-use-cases/overview.mdx, docs/faststore/docs/customization/dynamic-content/overview.mdx
1. Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-12592-override-use-cases) to set up the portal with this branch changes.
2. Access the following guides:
-  [Overview](https://developers.vtex.com/docs/guides/faststore/override-use-cases-overview)
- [Adding more icon options to the Alert component](https://developers.vtex.com/docs/guides/faststore/override-use-cases-adding-more-icon-options-to-the-alert-component)
- [Adding an image to the Alert component](https://developers.vtex.com/docs/guides/faststore/override-use-cases-adding-an-image-to-the-alert-component)
=> EDU-12592: Section override use cases

docs/faststore/components/molecules/order-summary.mdx, docs/faststore/components/molecules/product-card.mdx
Add Price With Taxes documentation
This PR adds news token and Props comming from Price wIth Taxes feature.
Access the Doc Portal
[Order Summary](https://faststore-site-git-docs-add-price-wit-taxes-docs-faststore.vercel.app/components/molecules/order-summary)
[Product Card](https://faststore-site-git-docs-add-price-wit-taxes-docs-faststore.vercel.app/components/molecules/product-card#design-tokens)
https://vercel.live/open-feedback/faststore-site-git-docs-add-price-wit-taxes-docs-faststore.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
=> Docs: Add taxes label design tokens

docs/faststore/docs/faststore-api/schema/mutations.mdx, docs/faststore/docs/faststore-api/schema/queries.mdx
There are some tag errors in the FastStore API Schema documentation. This PR aims to fix and solve some issues during the Dev Portal build.
=> Fix: FastStore API Schema tag errors

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-collecting-user-session-data.md
There were some letters in the builders and other places with the first letter in uppercase. Also I added a comma that was missing in a json example
- [ x ] Spelling and grammar accuracy (self-explanatory)
=> Case corrections and JSON formatting

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx
This PR updates some screenshots in the documentation, fix markdown issues and add a new section about the build logs feature. Reference: [EDU-12037](https://vtex-dev.atlassian.net/browse/EDU-12937)
I'm also working in the release note for it. The draft can be found [here](https://docs.google.com/document/d/1t9vF6V7sF6-L345Rl6qwL30ou8ufetzOT50NfCgkf3M/edit#heading=h.okvjkh8b4mqs).
[EDU-12037]: https://vtex-dev.atlassian.net/browse/EDU-12037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12037: Update WebOps dashboard doc

docs/guides/Master-Data/guides/pagination-in-the-master-data-api.md
=> add callout to master data pagination guide

docs/faststore/docs/headless-cms/2-setting-up-the-headless-cms.mdx, docs/faststore/docs/headless-cms/3-adding-content-types-and-sections.mdx
Change the Content Type name from "Custom Page" to "Landing Page," which is the correct name adopted by the team. Also, updated the first screenshot available in step 2. 
Reference: [EDU-12432](https://vtex-dev.atlassian.net/browse/EDU-12432)
[EDU-12432]: https://vtex-dev.atlassian.net/browse/EDU-12432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12432: Change "Custom Page" name to "Landing Page"

docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx
This PR adjusts some information according to the now working Integration between WebOps and CMS:
- Removed the callout mentioning the error in the integration between the WebOps and hCMS (since it's working now).
- Return the information about the Build Webhook URL field and how to set it. 
- Change `{workspace}` to `master` in the build URL example.
=> EDU-13644: Improve doc according to WebOps and Headless CMS integration

docs/faststore/docs/routing/managing-urls-with-redirects-and-rewrite-paths.mdx
LOC Review to the [Managing URLs with redirects and rewrite paths](https://developers.vtex.com/docs/guides/faststore/routing-managing-urls-with-redirects-and-rewrite-paths).
Sidebar updates: https://github.com/vtexdocs/devportal/pull/780
=> EDU-12795: LOC Review

docs/faststore/docs/customization/using-themes/components.mdx
Fixes in this PR:
- Doc typos.
- Mention about other data attributes. In the first step, there's a mention of the `data-fs-price-variant` data attributes with the `Listing` value, but the `data-fs-price-variant` does not need to be mentioned in this step, and the `Listing` value is mentioned in the second step.
=> EDU-12704: Fix data attribute

docs/release-notes/2024-10-30-webops-integration-with-headless-cms.md
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/810
=> EDU-13580: Release note: Fixed FastStore WebOps and Headless CMS integration

docs/faststore/docs/customization/building-sections/overrides/component-props.mdx
Revisando a trilha de Section override, foi notado alguns erros e melhorias que precisam ser feitos devido as últimas atualizações da FastStore. Esse PR corrigi e atualiza a documentação abaixo:
Doc: [Overriding native component's props](https://developers.vtex.com/docs/guides/faststore/overrides-component-props)
- Corrigir code snippte de `index.tsx` em 'Step 2 - Setting up the override'..
- Rodar `yarn dev` : Após o 'Step 2', adicionar o passo de rodar `yarn dev` para ver o novo component funcionando no localhost.
- Os 'Step 3' e 'Step 4' não são necessários, aqui estamos fazendo o override de prop para eventualmente aparecer na loja em production e não substituindo uma componente por outro no Headless CMS.
- Corrigir 'Step 5' para publicar o novo componente para loja em produção.
=> EDU-13702: Fix 'Overriding native component's props'

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-creating-a-native-form-for-your-store-users.md
=> fix code block on md store form guide

docs/faststore/docs/getting-started/3-faststore-cli.mdx, docs/faststore/docs/getting-started/requirements.mdx, docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx
Changes made in this PR:
- [FastStore CLI doc](docs/faststore/docs/getting-started/3-faststore-cli.mdx):  Add a 'Before you begin' section to mention the installation of Headless CMS, its dependencies and plugins.
- [Requirements doc](docs/faststore/docs/getting-started/requirements.mdx): Review the 'Install the Headless CMS and its dependencies' section and add the new section: 'Install Headless CMS plugins'.
- [Part 1: Configuring your VTEX account with the Headless CMS](docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx): Remove the instruction about Headless CMS plugins and add a new step in the 'Before you begin' about Headless CMS installation, its dependencies and plugins.
=> EDU-13838: Feedback for Installing FastStore CLI doc

docs/faststore/docs/headless-cms/overview.mdx
Changes in this PR:
- '[Before you begin'](https://github.com/vtexdocs/dev-portal-content/pull/1576/files#diff-e7246035c6c2e280c3df9b1a4bd96a621cca8aa3463415dff9766dc107f259fcR24): fixed link mentioning how to start a FastStore project.
- '[Headless CMS](https://github.com/vtexdocs/dev-portal-content/pull/1576/files#diff-e7246035c6c2e280c3df9b1a4bd96a621cca8aa3463415dff9766dc107f259fcR48-R55)': mentioned FastStore WebOps and Projects, and changed the property name ('Version' to 'Status').
- '[Content Types](https://github.com/vtexdocs/dev-portal-content/pull/1576/files#diff-e7246035c6c2e280c3df9b1a4bd96a621cca8aa3463415dff9766dc107f259fcR48-R55)': fixed button name and screenshot
=> EDU-13847: Review Headless CMS overview doc

docs/guides/Master-Data/guides/pagination-in-the-master-data-api.md
[EDU-13875](https://vtex-dev.atlassian.net/browse/EDU-13875)
[EDU-13875]: https://vtex-dev.atlassian.net/browse/EDU-13875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> remove _page parameter from master data pagination guide

docs/faststore/docs/managing-performance/improving-store-performance-with-preact.mdx
=> Fix Preact doc

docs/guides/Master-Data/getting-started-1/setting-up-triggers-in-master-data-v2.md
[EDU-13912](https://vtex-dev.atlassian.net/browse/EDU-13912)
[EDU-13912]: https://vtex-dev.atlassian.net/browse/EDU-13912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add info about spaces - triggers mdv2

docs/localization/i-cant-install-the-headless-cms-plugins-in-my-account.md
Tracked in task [LOC-17719](https://vtex-dev.atlassian.net/browse/LOC-17719)
[LOC-17719]: https://vtex-dev.atlassian.net/browse/LOC-17719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17719 - Windows user can't install Headless CMS plugins in 'my account' - troubleshooting documentation

docs/faststore/docs/customization/building-sections/creating-a-new-section.mdx
=> EDU-13701: Add new section: 'Adding styles to a new section'

docs/guides/vtex-io/Storefront-Guides/vtex-io-documentation-adding-custom-headers-to-your-store-framework-store.md
=> Fix slug - Adding custom headers to your Store Framework store

docs/faststore/docs/go-live/2-configuring-external-dns.mdx, docs/faststore/docs/reference/project-structure/overview.mdx
=> EDU-14061: Adds information about `subDomainPrefix` on go-live documentation

docs/guides/Orders/order-canceling-improvements.md
Fixed formatting errors and cURL for the endpoint `https://{accountName}.{environment}.com.br/api/orders/pvt/document/{orderId}/deny-cancellation-request`.
=> EDU-13928 - Update deny cancel order endpoint

docs/localization/vtex-io-documentation-6-buildingyourownstoretheme.md
Tracked in [LOC-17883](https://vtex-dev.atlassian.net/browse/LOC-17883).
[LOC-17883]: https://vtex-dev.atlassian.net/browse/LOC-17883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17883 - Building your own store theme documentation

docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-app-graphql-api.md
=> fix: external-marketplace-integration-app-graphql-api.md

docs/faststore/docs/getting-started/1-onboarding/overview.mdx, docs/faststore/docs/getting-started/requirements.mdx
=> EDU-14184: Update on WebOps doc about the master environment

docs/guides/Checkout/orders-2/create-a-regular-order-from-an-existing-cart.md
=> EDU-14497: Update create-a-regular-order-from-an-existing-cart.md

.gitignore, docs/guides/Orders/orders-feed.md
Added hyperlinks to commit and retrieve API documentation on the Feed v3 guide.
Also included `.DS_Store` on `gitignore` to ignore folders and subfolders.
=> Add hyperlinks to feed guide

docs/faststore/docs/getting-started/requirements.mdx
The `vtex.admin-cms-graphql@0.x ` dependency is no longer used.
=> Fix: Remove `vtex.admin-cms-graphql@0.x` dependency from hCMS docs

docs/localization/i-cant-install-the-headless-cms-plugins-in-my-account.md
Tracked in [LOC-19035](https://vtex-dev.atlassian.net/browse/LOC-19035).
[LOC-19035]: https://vtex-dev.atlassian.net/browse/LOC-19035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19035 - EDU-14397 - Headless CMS plugins error - troubleshooting documentation

docs/faststore/docs/getting-started/faststore-versions-and-support-levels.mdx, docs/faststore/docs/getting-started/overview.mdx, docs/guides/faststore/faststore.md
Updates on the navbar: the idea is to have a new guide inside the ['Getting started](https://developers.vtex.com/docs/guides/faststore/getting-started-overview)' (PR: `navigation.json`: https://github.com/vtexdocs/devportal/pull/909). Once we have the guide 'Upgrading to FastStore latest version', the idea is to have the 'Upgrading' category and inside it has the 'FastStore versions and support levels'
and the 'Upgrading to FastStore latest version' guides.
=> EDU-14356: FastStore versions and support levels

docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
This PR updates the following sentence to avoid any misunderstanding regarding using these experimental features in production:
Before: 
`All experimental [hooks and components](https://developers.vtex.com/docs/guides/faststore/building-sections-experimental-exports-hooks-and-components#list-of-hooks-and-components) are suffixed with _unstable, indicating that they are subject to change and may not be stable for use in production.` 
After: 
`All experimental [hooks and components](#list-of-hooks-and-components) are suffixed with `_unstable`, indicating they are available for use but may not function as expected or could have limitations with certain store customizations. Before deploying them in a production environment, make sure to test them to confirm compatibility with your store.`
=> EDU-14710: Feedback #4437 - Improvement

docs/faststore/docs/api-extensions/best-practices.mdx
Now the import path is: `...from '@faststore/core/src/experimental'`. Reference: [EDU-14780](https://vtex-dev.atlassian.net/browse/EDU-14780)
[EDU-14780]: https://vtex-dev.atlassian.net/browse/EDU-14780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14780: Update `useQuery` import

docs/faststore/docs/sdk/cart/use-cart.mdx, docs/faststore/docs/sdk/overview.mdx
This PR adds the `useCart` guide reviewed by the Localization team and also updates the [SDK overview](https://developers.vtex.com/docs/guides/faststore/sdk-overview) with the links for each SDK module.
`navigation.json`: https://github.com/vtexdocs/devportal/pull/930
=> EDU-13795: FastStore `useCart` - Add  LOC review

crowdin.yml
It fixes a part of the crowdin.yml file that was generating files with incorrect extensions.
=> Fix crowdin.yml file naming output

docs/guides/Orders/orders-feed.md
Fix variable name to `finished`, which does appear in the JSON file. Refers to [EDU-11430](https://vtex-dev.atlassian.net/browse/EDU-11430).
[EDU-11430]: https://vtex-dev.atlassian.net/browse/EDU-11430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-11430 - Fix variable name.

.github/workflows/changelog.yml, .versionrc, commitlint.config.js, package.json
Adding an automatic changelog based on this [RFC](https://docs.google.com/document/d/1gz90RrWEH3jRs3Tk67k7GLXGcXacmI6JGfelJNUfKq8/edit?tab=t.0).
Commit rules:
| Commit type | When to use | Allowed scopes |
| :---- | :---- | :---- |
| `new` | Add new documentation pages. Adding a scope is required (e.g. `new(guide): catalog overview`) | `guide`, `troubleshooting`, `release-notes` |
| `fix` | Fix typos, broken links, or minor corrections. Adding a scope is optional (e.g. `fix(broken-link): learn more`, `fix: marketplace name`). | `typo`, `broken-link, markdown` |
| `update` | Update existing documentation content | N/A |
| `remove` | Remove deprecated/outdated documentation pages | N/A |
| `loc` | Add or update translations/localization content | N/A |
| `media` | Add, update or remove …
=> feat: add changelog action and conventional commits

docs/faststore/components/molecules/search-products.mdx
Add new design tokens for the [`SearchProducts`](https://developers.vtex.com/docs/guides/faststore/molecules-search-products#design-tokens) based on the following PR: https://github.com/vtex/faststore/pull/2860
=> EDU-15253: Add new design tokens to `SearchProducts`

.github/scripts/check_frontmatter.py, .github/workflows/check-frontmatter.yml
Add "Check frontmatter" GitHub Action to validate frontmatter in Markdown files.
The action validates the frontmatter with the following fields:
|Field|Type|
|-|-|
|`title`|Non-empty `string`|
|`slug`|`string` with only lowercase letters, hyphens, and numbers. Must be equal the filename without extension.|
|`excerpt`|`string`|
|`createdAt`|`string` with ISO 8601 format (YYYY-MM-DDThh:mm:ss.sssZ)|
|`updatedAt`|`string` with ISO 8601 format (YYYY-MM-DDThh:mm:ss.sssZ)|
|`hidden`|`boolean`|
|`tags`|`list`|
|`type`|`string` with release note type. Must be one of: added, deprecated, fixed, improved, info, removed.|
The action validates the frontmatter fields for each documentation type as below:
|Field|Release note|Guide|Troubleshooting|FastStore|
|-|:-:|:-:|:-:|:-:|
|`title`    |⭕|⭕|⭕|⭕| …
=> Add "Check frontmatter" GitHub Action

docs/guides/vtex-io/GraphQL/graphql-authorization-in-io-apps.mdx
Restore markdown file. It was mistakenly left in the `docs/localization` folder in PR #2001 and deleted in PR #1936.
=> Restore "GraphQL Authorization in IO apps"

docs/guides/Orders/orders-feed.md
Add minimum and maximum value for `messageRetentionPeriodInSeconds` field. Refers to [EDU-12948](https://vtex-dev.atlassian.net/browse/EDU-12948).
[EDU-12948]: https://vtex-dev.atlassian.net/browse/EDU-12948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12948 - Add min and max value for field

docs/guides/Integration-Guides/erp-integration-guide/order-modifications.md
Add new Change V2 exception codes to the table. Additionally, turn the HTML tables into Markdown. Refers to [EDU-16040](https://vtex-dev.atlassian.net/browse/EDU-16040).
[EDU-16040]: https://vtex-dev.atlassian.net/browse/EDU-16040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-16040 - Add new exception codes and use Markdown for the tables
