.gitignore, fetch-docs/get-documentation.js, fetch-docs/package-lock.json, fetch-docs/package.json
Adds a script for retrieving VTEX's documentation from Readme and creating folders from category and document slugs.
More information can be found [here](https://www.notion.so/vtexhandbook/Criar-script-para-puxar-documenta-o-do-Readme-e-criar-estrutura-de-pastas-91be7e622c934abab61058b0c73d326b)
=> Feature/Get Documentation

docs/guides/Integration Guides/payments-integration-guide/payments-integration-implementing-a-payment-provider.md
Added new callout and updated reference links
=> Added new callout and updated reference links

docs/guides/Getting Started/search-overview.md
Ajustando links das imagens do guia Search Overview
=> Ajustando imagens do Search Overview

docs/guides/Getting Started/payments-overview.md
Ajustando a imagem Payment Overview
=> Ajustando a imagem Payment Overview

docs/vtex-io/Store Framework Apps/basic-components/vtex-product-price.md
=> adding missing <\img> tag on vtex-product-price.md

docs/release-notes/oms-ui-deprecation.md
The UI of the All Orders module is being deprecated and it was decided to reinforce that information through Developer Portal.
=> Release note oms UI deprecation

docs/release-notes/oms-ui-deprecation.md
=> Fix date oms-ui-deprecation.md

docs/guides/VTEX inStore/how-to-manage-instore-data/integrating-instore-to-a-new-payment-acquirer.md
Correcting blocks formating for error
> Error: There are incorrectly formatted code blocks in this file
=> Correcting blocks formating on integrating-instore-to-a-new-payment-acquirer.md

readme-api-md/VTEX inStore/create-a-middleware-to-issue-tax-coupons-for-instore.md
Unpublish create-a-middleware-to-issue-tax-coupons-for-instore.md as asked on this [thread](https://vtex.slack.com/archives/C015Z67CJS2/p1671569754483309?thread_ts=1657718472.283109&cid=C015Z67CJS2)
=> Unpublish create-a-middleware-to-issue-tax-coupons-for-instore.md

docs/vtex-io/Store Framework Apps/regionalization-beta.md, readme-api-md/VTEX Session/sessions-system-overview.md
=> fix: md errrors

README.md
=> Update broken link README.md

docs/vtex-io/Storefront Guides/b2b-setup/installing-b2b-easy-set-up.md
=> Fix callout formatting in installing-b2b-easy-set-up.md

docs/vtex-io/Storefront Guides/b2b-setup/access-control-list.md
=> Fix access-control-list.md

docs/vtex-io/Store Framework Apps/b2b-components/vtex-shopper-location.md
=> Fix Shopper Location code blocks indent

docs/vtex-io/Storefront Guides/b2b-setup/installing-b2b-easy-set-up.md
=> Add missing closing tag - B2B Easy Set Up

docs/vtex-io/Store Framework Apps/vtex-b2b-suite/vtex-b2b-quotes.md, docs/vtex-io/Store Framework Apps/vtex-b2b-suite/vtex-storefront-permissions-ui.md, docs/vtex-io/Store Framework Apps/vtex-b2b-suite/vtex-storefront-permissions.md
=> Fix B2B docs

docs/vtex-io/Reference/graphql-apis/rewriter.md
=> fixing </td> issue

docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-business-guidelines-marketing-assets.md
=> removing <i> tag and changing excerpt description

docs/vtex-io/Storefront Guides/b2b-setup/installing-b2b-easy-set-up.md
=> Fix installing-b2b-easy-set-up.md

docs/guides/Payments/payments-configuration-guides/setting-up-merchant-id-in-apple-pay.md
Updated "Setting up Merchant ID in Apple Pay" links.
=> Update "Setting up Merchant ID in Apple Pay" links

docs/release-notes/cardholder-document-configuration.md
=> Fixed reference link spaces

docs/guides/Checkout/configuration-section-api-quick-start-guides/clear-orderform-message-field-from-cart.md, docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md, docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md, docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
Created new configuration section quick start guides.
=> Created new configuration guides section

docs/guides/Integration Guides/payments-integration-guide/payments-integration-payment-methods.md
Fixed "Payment Methods" links and callout formats.
=> Fixed "Payment Methods" links and callout formats.

docs/guides/Integration Guides/gift-card-integration-guide/gift-card-integration-guide-system-architecture.md
Fixed "Gift Card system architecture" links
=> Fixed "Gift Card system architecture" links

docs/guides/Integration Guides/payments-integration-guide/payments-integration-purchase-flows.md
Fixed "Purchase Flows" link and callout format.
=> Fixed "Purchase Flows" link and callout format

docs/guides/Getting Started/subscriptions.md
=> New subscriptions guide

docs/guides/Pricing Hub/pricing-hub-overview.md
=> Fix pricing-hub-overview.md

docs/vtex-io/Store Framework Apps/b2b-components/vtex-location-availability.md
=> Fix URL and image - Location Availability

docs/guides/Checkout/configuration-section-api-quick-start-guides.md
Create Configuration Section Api Quick Start Guides page
=> Create Configuration Section Api Quick Start Guides page

docs/guides/Checkout/configuration-section-api-quick-start-guides/clear-orderform-message-field-from-cart.md
Added Title "Clear orderForm message field from cart"
=> Added Title "Clear orderForm message field from cart"

docs/guides/Orders/unofficial-checkout-api-deprecation.md
=> Add content unofficial checkout api deprecation 

docs/guides/Integration Guides/payments-integration-guide/payments-integration-payment-app.md
=> Fixed "Payment App" links

docs/guides/Integration Guides/payments-integration-guide/updating-sku-specifications-with-catalog-api.md
Fixed "Updating SKU Specs" links.
=> Fixed "Updating SKU Specs" links.

docs/guides/Checkout/cart-attachments-section-api-quick-start-guides.md
Added title information "Cart Attachments" page
=> Added title information "Cart Attachments" page

docs/vtex-io/Store Framework Apps/layout-apps/vtex-tab-layout.md
Fixed typo | "tab-layou" to "tab-layout"
=> Fixed typo "tab-layou"

docs/guides/legacy-cms/creating-gift-lists.md
=> Update creating-gift-lists (erros de markdown e havia um texto escrito em português, traduzi p/ inglês)

docs/guides/Orders/outdated-checkout-api-deprecation.md
=> Update api deprecation name

docs/release-notes/outdated-checkout-endpoint-deprecation.md
=> Release note api breaking change

docs/vtex-io/Store Framework Apps/vtex-gift-list/vtex-list-listmigration.md
=> Add vtex-list-listmigration.md

docs/guides/Integration Guides/pii-compliant-accounts/profile-system.md
=> fixing formatting in callouts

docs/guides/Integration Guides/external-seller-integration-guide/external-seller-integration-connector.md
=> adding new links for the manage suggestions page

docs/guides/Getting Started/getting-started/getting-started-authentication.md
Correcting hashlinks of the table in the [authentication overview for devs](https://developers.vtex.com/docs/guides/getting-started-authentication#app-authentication).
=> correcting hashlinks

docs/release-notes/safedata-can-now-block-the-anonymous-creation-of-documents-for-all-master-data-entities.md
=> Update SafeData release note date

docs/vtex-io/Store Framework Apps/pixel-apps/vtex-facebook-fbe.md
=> updating script in Required Actions section

docs/guides/VTEX Tracking/vtex-tracking-overview.md
=> Fix vtex-tracking-overview.md

docs/guides/Catalog Seller Portal/catalog-api-seller-portal-overview.md
=> Fix catalog-api-seller-portal-overview.md

.github/workflows/check-links.yml, docs/guides/Search/consult-store-search-terms-information.md
=> Add workflow file

.github/workflows/markdown-lint.yml, docs/guides/Subscriptions/subscriptions-api-v3-overview.md
=> Add Linter Workflow

.github/workflows/markdown-lint.yml
=> Add disable rules

docs/release-notes/safedata-can-now-block-the-anonymous-creation-of-documents-for-all-master-data-entities.md
- Adding the frontmatter `excerpt`
- Adding release tags
=> Minor adjustments to jan23 SafeData release note

docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-submitting-your-app-in-the-vtex-app-store.md
=> adding info on the Before You Start section

docs/release-notes/outdated-checkout-endpoint-deprecation.md
=> Add excerpt release note breaking change

docs/vtex-io/Reference/concepts/vtex-io-documentation-routes.md
=> Fixed 404 vtex io documentation routes.md

docs/release-notes/new-parameters-for-installments-in-payment-provider-protocol.md
=> Fixed 404 links installments payment prov protc.md

docs/vtex-io/Perks/best-practices/vtex-io-documentation-best-practices-for-rendering-images.md
=> Fixed 404 links best practices rendering images.md

docs/vtex-io/Store-Framework-Apps/basic-components/vtex-product-summary.md, docs/vtex-io/Store-Framework-Apps/deprecated/vtex-product-summary-productsummaryspecificationbadges.md
=> adding deprecation reference

docs/release-notes/guide_template.md
=> release note for badges app

docs/vtex-io/Storefront-Guides/styling-your-store/vtex-io-documentation-contributing-with-new-css-handles.md
=> Fixed 404 links vtex io doc contrib css hands.md

docs/release-notes/new-endpoints-for-subscriptions-v3-available.md
=> Fixed 404 link subscriptions v3 available.md

docs/guides/Orders/orders-feed.md
=> Fixed 404 links - orders-feed.md

docs/guides/Search/search-api-overview.md
=> Fixed 404 link - search api overview.md

docs/vtex-io/Perks/best-practices/vtex-io-documentation-best-practices-for-rendering-images.md
=> Fixed 404 links - Rendering images.md

docs/guides/Orders/outdated-checkout-api-deprecation.md
Make a description more precise about QraphQL queries.
=> improve description graphql breaking change

docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-setting-your-apps-billing-model.md
=> fix: improve JSON examples

docs/guides/Checkout/fulfillment-checkout-section-api-quick-start-guides/list-pickup-points-by-location.md
PR created to publish the new Checkout Quick Start Dev Guide "List Pickup points by location"
=> New Dev Guide List Pickup points by location

docs/guides/Checkout/fulfillment-checkout-section-api-quick-start-guides/get-address-by-postal-code.md
PR created to publish the new Checkout Quick Start Dev Guide "Get address by postal code"
=> New Dev Guide Get address by postal code

docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-architecture.md
=> Fixed 404 links - external mkt architect.md

docs/vtex-io/Store-Framework-Apps/vtex-store-components.md, docs/vtex-io/Store-Framework-Apps/vtex-store-components/test-vtex-store-components.md
=> Removed Travis CL section - vtex store comps.md

docs/vtex-io/Store-Framework-Apps/vtex-my-account.md
Add information about how VTEX does not offer support to customized "My accounts".
=> add my account callout vtex support

docs/guides/Integration-Guides/external-marketplace-integration-guide/deprecated-how-to-collect-orders-from-sales-channels.md
=> Fix 404 links - [Deprecated] How to collect orders from sales channels

docs/guides/Checkout/white-label-sellers-selection-algorithm/update-an-account-orderform-configuration.md
=> Fix 404 links - Update an account's orderForm configuration

docs/guides/Checkout/shopping-cart-section-api-quick-start-guides.md, docs/release-notes/fix-body-param-name-from-create-or-update-promotion-endpoint.md, docs/release-notes/new-erp-integration-guide-is-now-available.md, docs/release-notes/new-marketplace-endpoints-available-request-review.md, docs/release-notes/vtex-tracking-api-changes-in-all-paths.md
=> Fix 404 links

docs/guides/Integration-Guides/catalog-integration/how-to-activate-an-sku.md
=> Fix 404 errors - How to activate an SKU

docs/guides/Getting-Started/checkout-overview.md
=> Fix 404 link - Add and handle custom information in the order

docs/guides/Checkout/cart-attachments-section-quick-start-guides/add-marketing-data-to-the-cart.md
Fixed 404 link and updated block code formats
=> Fixed 404 link and updated block code formats

docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
=> Fix 404 link - Get an account's orderForm configuration

docs/release-notes/improvement-price-consistency-checkout-discounts-installments.md
=> Fix 404 links - Price consistency at Checkout Release Notes

docs/release-notes/new-quick-start-guides-for-checkout.md
=> Fix 404 link - Shopping Cart Section

docs/vtex-io/Store-Framework-Apps/vtex-checkout-ui-custom.md
=> Fix 404 link - Get orderForm configuration

docs/release-notes/improvements-in-checkout-api-documentation.md
=> Fix 404 links - Improvements in Checkout API documentation

docs/guides/UI-Customization/vtexjs.md
=> Fix 404 link - vtexjs - orderForm documentation

docs/guides/Checkout/orders-2/create-a-regular-order-from-an-existing-cart.md
PR created to publish the new Checkout Quick Start Dev Guide "Create a regular order from an existing cart"
=> New Dev. Guide - Create a regular order from an existing cart

docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/get-cart-information-by-id.md
PR created to update  procedure "Getting shopping cart ID" (EDU-9024).
=> Update Getting shopping cart ID procedure

README.md, docs/guide_template.md
Added information about two fields to be added in the frontmatter:
- hidePaginationPrevious: false
- hidePaginationNext: false
=> Update readme new components

docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
Added more details about creating channels based on this [issue](https://github.com/vtexdocs/dev-portal-content/issues/218) created.
Also corrected links with new URLs.
=> Updating doc with details on create channel endpoint and corrected links

docs/release-notes/custom-io-apps-need-to-add-the-listorders-resource.md
The CX team required a deadline for the product team to start the breaking change, because clients were uncomfortable and unsatisfied with the subtle change.
=> Add date breaking change listorders resource

docs/release-notes/new-options-for-adding-and-removing-modules-from-the-kit-look-app.md
=> adding release type

README.md
=> Improving Readme sections on adding images

docs/guides/Checkout/orders-2.md
PR open to add "Create a regular order from an existing cart" reference - Orders article.
=> Orders - Add Create a regular order from an existing cart reference

docs/release-notes/facebook-domain-verification-app-1.md
Changed VTEX IO Docs link:
https://vtex.io/docs/components/pixel/vtex.facebook-domain-verification/
To new Developer Portal link:
https://developers.vtex.com/docs/apps/vtex.facebook-domain-verification
=> Fixed broken link

docs/guides/Integration-Guides/headless-commerce/headless-authentication.md
=> Fix markdown unordered list

docs/guides/Checkout/region-section-api-quick-start-guides/get-sellers-by-region-or-address.md
PR create to publish a new Quick-Start Dev. Guide: "Get sellers by region or address"
=> New Dev. Guide Get sellers by region or address

docs/guides/Checkout/fulfillment-checkout-section-api-quick-start-guides.md
New Checkout Fulfillment Quick-Start guide page created.
=> New Checkout Fulfillment Quick-Start guide page

docs/release-notes/endpoint-renamed-and-updated-get-sellers-by-region
PR created to publish the release notes: Endpoint renamed and updated: Get sellers by region
=> Release Notes -  Endpoint renamed and updated: Get sellers by region

docs/guides/Checkout/region-section-api-quick-start-guides.md
New Region Quick-Start guide page created.
=> New Region Quick-Start guide page

docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-delivery-validation.md
=> Fix fulfillment simulation URL

docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-invoice-tracking.md
=> Fix steps in External Marketplace guide

docs/guides/Getting-Started/fulfillment.md
Fixed broken links, typos and small improvements.
=> General improvements fulfillment guide

docs/guides/Integration-Guides/erp-integration-guide/erp-integration-import-inventory.md
Fixed broken links and updated other links.
=> Fix broken links import inventory doc

docs/guides/Checkout/orders-2.md
PR created to update article name.
=> Updated article name - Order placement

docs/guides/Integration-Guides/catalog-integration/how-to-implement-product-color-variation.md
=> Improve product color variation guide

docs/guides/Checkout/checkout-api-overview.md
Updated endpoint description Title - Get sellers by region or address
=> Updated endpoint description Title - Get sellers by region or address

docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/create-a-new-cart.md
PR created to add a new query (forceNewCart) information, update content and rename the endpoint (from "Create a new cart" to "Get current or create a new cart"). (EDU-9188).
=> Updated and renamed "Get current or create a new cart" Dev. Guide

docs/guides/Checkout/shopping-cart-section-api-quick-start-guides.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/get-cart-information-by-id.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/remove-all-personal-data.md
PR created to update "Get current or creat a new cart" references.
=> Updated Get current or create a new cart reference

docs/guides/Fulfillment/vtex-shipping-network/vtex-shipping-network-labels-integration.md
=> Insert image vtex shipping network labels integration

docs/guides/Checkout/orders-2/create-a-regular-order-using-the-checkout-api.md
PR created to fix a typo (“”).
=> Fix typo - “”

docs/release-notes/endpoint-renamed-and-updated-get-sellers-by-region
PR created to add "Improved" information.
=> Added "Improved" information.

docs/release-notes/deprecation-of-apps-graphql@2.x.md
=> Publish apps-graphql@2.x deprecation release note

docs/release-notes/deprecation-of-apps-graphql@2.x.md
=> Correct apps-graphql@2.x deprecation date

docs/guides/Checkout/orderform-fields.md
Someone said there was a problem with C&A because this field's description did not include all possible values.
=> improve shippingDate description

docs/guides/Integration-Guides/erp-integration-guide/change-order.md
=> Translate messages change order

docs/guides/Marketplace/marketplace-api-overview.md
Fixing broken links and add missing sections
=> Marketplace API Overview

README.md
Including "How to update the left navigation after changing an endpoint’s path"
=> include FAQ update navigation after changing path

README.md
=> edit repo readme.md

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
=> Add a callout in the GTM documentation

docs/guides/Getting-Started/checkout-overview.md
PR created to update endpoint names and add a new article.
=> Update endpoint names - Checkout overview

docs/vtex-io/Store-Framework-Apps/vtex-b2b-suite/vtex-b2b-organizations.md
=> Replaced markdown on images to HTML

docs/guides/Search/consult-product-search-information.md, docs/guides/Search/get-a-list-of-the-possible-facets-for-a-specific-search.md, docs/guides/Search/get-banner-list-for-a-specific-search.md
=> Add Intelligent Search guides

docs/guides/Integration-Guides/payments-integration-guide/pse-payment-method.md
PR created to publish the new article PSE - Payment Method (EDU-5667).
=> New article - PSE Payment Method

docs/vtex-io/Store-Framework-Apps/advanced-components/vtexventures-livestreaming.md
Fixed the images' paths to reflect the new ones.
=> Live Streaming - Update Images path

docs/release-notes/pse-payment-method-for-colombian-customers.md
PR create to publish the Release Notes - PSE Payment method
=> Release Notes - PSE Payment method

docs/release-notes/pse-payment-method-for-colombian-customers.md
PR created to fix links spaces
=> Fix links spaces

docs/guides/Getting-Started/getting-started/getting-started.md
Adds new sections to the getting started article, and fixes links
=> Add new doc links in getting started

docs/release-notes/addition-of-signature-parameter-on-callback-url-for-payment-integrations.md
Update accomplishment date (EDU-9551).
=> Update accomplishment date

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
Fixed the path for the images.
=> Fix: Images' path for the Google Tag manager doc. 

docs/guides/Getting-Started/orders-overview.md
=> Fix broken links orders guide

docs/vtex-io/Reference/graphql-apis/search-graphql.md
=> fix table of contents and edit orderBy criteria descriptions in search-graphql guide

docs/release-notes/2019-11-25-product-specifications.md
=> fix broken links in release notes

docs/release-notes/master-data-v2-orders-entity-deprecation.md
Publishing the release note about the deprecation of the mdv2 orders entity.
=> Orders mdv2 entity deprecation - Release note

docs/guides/Integration-Guides/payments-integration-guide/layout-development-guide-for-payment-methods-in-smart-checkout-vtex.md
I believe this guide is breaking the dev portal and am fixing it.
=> Fix broken payments guide

docs/vtex-io/Perks/best-practices/vtex-io-documentation-best-practices-for-optimizing-performance.md
…e.md
- [ x ] Fix (fix a documentation error)
Fixed the path for Store Settings in the Admin
=> Fix: Store Settings path in Admin

docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack.md
Correct duplicated title and add hyperlinks.
=> Correct duplicated title VTEX Pick and Pack

docs/guides/Payments/antifraud-provider-protocol-overview.md
PR created to remove the Help Center reference.
=> Fix incorrect Help Center reference

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
PR created to fix broken links and callout formats, and make editorial improvements to the article "Pix: Instant Payments in Brazil" (EDU-9714).
=> Complete editorial update

docs/guides/Integration-Guides/erp-integration-guide/erp-integration-import-products.md
=> fix link to google import app + small edits

docs/guides/Checkout/checkout-error-codes.md
PR created to fix title and table formats.
=> Fix title and table format

docs/guides/Integration-Guides/gift-card-integration-guide/gift-card-integration-guide-provider-protocol.md
PR created to fix broken links and code format (EDU-9770).
=> Fix broken links and code format.

docs/guides/Fulfillment/vtex-shipping-network/vtex-shipping-network-labels-integration.md
The environment was incorrect and has been changed.
=> VTEX shipping network label environment correction

docs/release-notes/2023-04-20-New Coupons v2 API, docs/release-notes/2023-04-20-new-coupon-v2-api
=> Create 2023-04-20-New Coupons v2 API

docs/vtex-io/Getting-Started/vtex-io-documentation-what-is-vtex-io.md
Fixvtex-io-documentation-what-is-vtex-io.md
It relates to [LOC-10585](https://vtex-dev.atlassian.net/browse/LOC-10585) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit))
[LOC-10585]: https://vtex-dev.atlassian.net/browse/LOC-10585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-what-is-vtex-io.md

docs/guides/Getting-Started/fulfillment.md
Changed the Fulfillment guide name.
=> Update Fulfillment guide title

docs/guides/Integration-Guides/payments-integration-guide/how-the-integration-protocol-between-vtex-and-antifraud-companies-works.md
PR created to update antifraud provider protocol images.
=> Update antifraud provider protocol images

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-implementing-a-payment-provider.md, docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md, docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-homologation.md, docs/guides/Integration-Guides/payments-integration-guide/pse-payment-method.md
PR was created to update articles  (removing reference to "List Payment Methods" endpoint) (EDU-9843).
=> Update articles (remove list payment methods endpoint references)

docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
Fixget-an-account-orderform-configuration.md
It relates to [LOC-10431](https://vtex-dev.atlassian.net/browse/LOC-10431) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit))
[LOC-10431]: https://vtex-dev.atlassian.net/browse/LOC-10431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on get-an-account-orderform-configuration.md

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-installing-google-tag-manager.md
=> new content gtm

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-migrating-google-tag-manager-app.md, docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-sending-custom-events-to-google-tag-manager.md, docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
=> new content for configuring

docs/release-notes/deprecation-of-list-payment-methods-endpoint.md
PR created to publish Release Notes "Deprecation of List Payment Methods endpoint" (EDU-9483).
=> Deprecation of List Payment Methods endpoint

docs/guides/legacy-cms/list-of-controls-for-templates.md
It relates to task [LOC-10577](https://vtex-dev.atlassian.net/browse/LOC-10577) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10577]: https://vtex-dev.atlassian.net/browse/LOC-10577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on list-of-controls-for-templates.md

docs/release-notes/deprecation-of-list-payment-methods-endpoint.md
PR created to fix information (excerpt e type: deprecated).
=> Fix information (excerpt e type: deprecated).

docs/guides/Integration-Guides/api-guides/setting-up-dkim-for-transactional-emails.md
It relates to task [LOC-10629](https://vtex-dev.atlassian.net/browse/LOC-10629) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10629]: https://vtex-dev.atlassian.net/browse/LOC-10629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on setting-up-dkim-for-transactional-emails.md

docs/guides/Orders/orders-feed.md
It relates to task [LOC-10484](https://vtex-dev.atlassian.net/browse/LOC-10404) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10484]: https://vtex-dev.atlassian.net/browse/LOC-10484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on orders-feed.md

docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available.md
It relates to task [LOC-10610](https://vtex-dev.atlassian.net/browse/LOC-10610) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10610]: https://vtex-dev.atlassian.net/browse/LOC-10610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-making-your-new-app-version-publicly-available.md

docs/vtex-io/Storefront-Guides/styling-your-store/vtex-io-documentation-using-css-handles-for-store-customization.md
It relates to task [LOC-10545](https://vtex-dev.atlassian.net/browse/LOC-10545) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10545]: https://vtex-dev.atlassian.net/browse/LOC-10545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-using-css-handles-for-store-customization.md

docs/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-enabling-order-form-optimization.md
This PR review the Order Form doc and also fix the VTEX Admin path mentioned to enable orderForm optimization.
=> Fix: Order Form doc 

docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-releasing-a-new-app-version.md
It relates to task [LOC-10563](https://vtex-dev.atlassian.net/browse/LOC-10563) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10563]: https://vtex-dev.atlassian.net/browse/LOC-10563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-releasing-a-new-app-version.md

docs/guides/Getting-Started/orders-overview.md
Correcting markdown problems by removing a component.
=> Adjust markdown orders guide

docs/guides/Getting-Started/getting-started/getting-started.md
It relates to task [LOC-10653](https://vtex-dev.atlassian.net/browse/LOC-10653) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10653]: https://vtex-dev.atlassian.net/browse/LOC-10653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on getting-started.md

docs/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-1-basicsetup.md
It relates to task [LOC-10643](https://vtex-dev.atlassian.net/browse/LOC-10643) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10643]: https://vtex-dev.atlassian.net/browse/LOC-10643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-1-basicsetup.md

docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-becoming-a-registered-vtex-app-store-developer.md
=> Fix partner application form link

docs/guides/Fulfillment/vtex-shipping-network/vtex-shipping-network-labels-integration.md
Add content in vtex shipping network labels integration about configuring shipping labels printing format.
=> Add content vtex shipping network labels integration

docs/guides/VTEX-Sales-App/integration-vtex-sales-app-local-stock-sale.md
=> Rename On Hands to Local stock sale

docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-promoting-a-workspace-to-master.md
It relates to task [LOC-10723](https://vtex-dev.atlassian.net/browse/LOC-10723) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10723]: https://vtex-dev.atlassian.net/browse/LOC-10723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixes of i18n on vtex-io-documentation-promoting-a-workspace-to-master.md

docs/guides/Integration-Guides/recaptcha-beta.md, docs/guides/Integration-Guides/recaptcha/implementing-recaptcha-in-integrations-beta.md
Updating the reCAPTCHA integration guide. This PR publishes two hidden beta articles that should replace the existing ones in the future:
- [reCAPTCHA](https://developers.vtex.com/docs/guides/recaptcha)
- [Implementing reCAPTCHA in integrations](https://developers.vtex.com/docs/guides/implementing-recaptcha-in-integrations)
=> Recaptcha updates

docs/guides/Integration-Guides/data-privacy/data-residency.md
=> Data residency - Adjusting mermaid image color

docs/guides/Integration-Guides/data-privacy/data-residency.md, docs/guides/Integration-Guides/data-privacy/profile-system.md, docs/guides/Integration-Guides/pii-data-architecture.md
=> PII architecture - change file name, slug and title

docs/guides/Integration-Guides/data-privacy/profile-system.md, docs/guides/Integration-Guides/pii-data-architecture.md
=> Adding Profile System Audit information

docs/guides/Integration-Guides/headless-commerce/headless-cart-and-checkout.md
=> headless checkout markdown list fix

docs/release-notes/2023-06-06-new-integration-guide-headless-commerce.md
=> Headless integration guide release note

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-installing-google-tag-manager.md, docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
It relates to Task [LOC-11041](https://vtex-dev.atlassian.net/browse/LOC-11041).
[LOC-11041]: https://vtex-dev.atlassian.net/browse/LOC-11041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on two google-tag-manager related files

docs/guides/Getting-Started/payments-overview.md
It relates to task [LOC-10735](https://vtex-dev.atlassian.net/browse/LOC-10735) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10735]: https://vtex-dev.atlassian.net/browse/LOC-10735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on payments-overview.md

docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-creating-a-development-workspace.md
It relates to task [LOC-10774](https://vtex-dev.atlassian.net/browse/LOC-10774) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10774]: https://vtex-dev.atlassian.net/browse/LOC-10774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-creating-a-development-workspace.md

docs/vtex-io/Perks/best-practices/vtex-io-documentation-best-practices-for-optimizing-performance.md
It relates to task [LOC-10814](https://vtex-dev.atlassian.net/browse/LOC-10814) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10814]: https://vtex-dev.atlassian.net/browse/LOC-10814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-best-practices-for-optmizing-performance.md

docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
It relates to task [LOC-10435](https://vtex-dev.atlassian.net/browse/LOC-10435) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10435]: https://vtex-dev.atlassian.net/browse/LOC-10435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on get-and-update-the-seller-exchange-window.md

docs/guides/Checkout/marketing-utms/check-marketing-utms-used-at-checkout.md
PR created to update the IPS cookie information (EDU-10083).
=> IPS cookie information updated

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-7-consuming-data.md
It relates to task [LOC-11476](https://vtex-dev.atlassian.net/browse/LOC-11476) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-11476]: https://vtex-dev.atlassian.net/browse/LOC-11476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-7-consuming-data.md

docs/vtex-io/Reference/graphql-apis/graphql-ide.md
It relates to task [LOC-10789](https://vtex-dev.atlassian.net/browse/LOC-10789) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10789]: https://vtex-dev.atlassian.net/browse/LOC-10789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on graphql-ide.md

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-5-defining-styles.md
It relates to task [LOC-10801](https://vtex-dev.atlassian.net/browse/LOC-10801) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10801]: https://vtex-dev.atlassian.net/browse/LOC-10801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-5-defining-styles.md

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-2-basic-development-setup-in-vtex-io.md
It relates to task [LOC-10785](https://vtex-dev.atlassian.net/browse/LOC-10785) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10785]: https://vtex-dev.atlassian.net/browse/LOC-10785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-2-basic-development-setup-in-vtex-io.md

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-migrating-google-tag-manager-app.md
This PR improves the documentation for migrating to the new version of GTM. Previously, the documentation was focused on UA, which is now outdated, considering the new app version that supports GA4. Therefore, this update removes the obsolete content and provides relevant information for the GA4 migration process.
=> Improvement: Feedback #3002

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-implementing-a-payment-provider.md
PR created to update custom payment information (Implementing a Payment Provider article) (EDU-7364).
=> Custom payment information updated

docs/guides/Promotions/creating-and-managing-coupons-with-promotions-api.md
=> fix links and formatting

docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-promoting-a-workspace-to-master.md, docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-publishing-an-app.md
=> Corrections in New App Version section

.github/workflows/preview.yml
To add an action for collecting the updated markdown files and generating links for previewing the modifications in the Developers Portal.
Try making some changes in markdown files and pushing those changes to this branch. The preview action should run and provide URLs for acessing the modified documentation pages in the "Preview Links" comment below. Keep in mind that the action may end up not finding the corresponding pages in the Developers Portal. This may be due to missing frontmatter, missing slug property in frontmatter or missing slug in the navigation.json file. Also, make sure you revert your changes before finishing reviewing this PR.
=> Preview Action

docs/vtex-io/Store-Framework-Apps/store-components.md, docs/vtex-io/Store-Framework-Apps/store-components/vtex-store-components-searchbar.md
This PR aims to fix the error while navigating the store components overview page.
=> Fix: Update `store-components.md`

docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md, docs/guides/Integration-Guides/sent-offers-integration-guide-connectors/offer-management-sdk.md
=> Info offer management integration

docs/guides/UI-Customization/vtexjs/vtexjs-for-checkout.md
It relates to task [LOC-10727](https://vtex-dev.atlassian.net/browse/LOC-10727) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10727]: https://vtex-dev.atlassian.net/browse/LOC-10727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtexjs-for-checkout.md

docs/guides/Integration-Guides/erp-integration-guide/erp-integration-set-up-order-integration.md
It relates to task [LOC-10778](https://vtex-dev.atlassian.net/browse/LOC-10778) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10778]: https://vtex-dev.atlassian.net/browse/LOC-10778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on erp-integration-set-up-order-integration.md

docs/guides/Search/how-search-parameters-work.md
It relates to task [LOC-10702](https://vtex-dev.atlassian.net/browse/LOC-10702) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10702]: https://vtex-dev.atlassian.net/browse/LOC-10702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on how-search-parameters-work.md

docs/vtex-io/Store-Framework-Apps/vtex-b2b-suite/vtex-b2b-organizations.md
It relates to task [LOC-10743](https://vtex-dev.atlassian.net/browse/LOC-10743) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10743]: https://vtex-dev.atlassian.net/browse/LOC-10743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-b2b-organizations.md

docs/guides/Checkout/orderform-fields.md
PR created to update StorePreferencesData information (EDU-10163).
=> StorePreferencesData update information

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md
PR created to remove beta callout (Payment Provider Framework) (EDU-10150).
=> Payment Provider Framework beta callout removed

docs/guides/Integration-Guides/payments-integration-guide/google-pay-processing-information-for-payment-providers-and-anti-fraud.md
PR created to publish the new article: "Google Pay: processing information for payment providers and anti-fraud".
=> New article Google Pay processing information

docs/release-notes/cardholder-document-configuration-release.md
Name of a Release Notes File has been updated (cardholder-document-configuration.md >> cardholder-document-configuration-release.md). The previous file was in conflict with the Dev. **Guide Cardholder Document Configuration**.
=> Update Release Notes file name

docs/vtex-io/Storefront-Guides/vtex-io-documentation-migrating-cms-settings-after-major-update.md
It relates to task [LOC-10766](https://vtex-dev.atlassian.net/browse/LOC-10766) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).
[LOC-10766]: https://vtex-dev.atlassian.net/browse/LOC-10766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes of i18n on vtex-io-documentation-migrating-cms-settings-after-major-update.md

docs/guides/Payments/payments-configuration-guides/implementing-a-pre-analysis-antifraud-flow-for-debit-card-transactions.md
PR created to fix a image tag (</img>).
=> Fixed image tag

docs/release-notes/2023-07-07-change-in-the-sku-notification-behavior.md
Adding release notes about the Change in the SKU notification behavior, as part of [EDU-10067](https://vtex-dev.atlassian.net/browse/EDU-10067).
[EDU-10067]: https://vtex-dev.atlassian.net/browse/EDU-10067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add release notes - change in the sku notification behavior

docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md, docs/guides/Integration-Guides/sent-offers-integration-guide-connectors/offer-management-sdk.md
=> EDU-10219 | Fix render guides Dev portal

docs/release-notes/application-form-to-access-vtex-io-builders-is-no-longer-required.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-builders.md
=> VTEX IO builders application form removal

docs/release-notes/application-form-to-access-vtex-io-builders-is-no-longer-required.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-builders.md
=> Add builder-hub version requirement

docs/vtex-io/Storefront-Guides/b2b-setup/access-control-list.md
=> edit access-control-list.md

docs/guides/Message-Center/templates/how-to-set-up-functions-in-the-message-center-templates.md
[EDU-10259](https://vtex-dev.atlassian.net/browse/EDU-10259)
[EDU-10259]: https://vtex-dev.atlassian.net/browse/EDU-10259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> message center functions - fix formatting and writing, improve descriptions

docs/vtex-io/Storefront-Guides/google-tag-manager.md, docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-installing-google-tag-manager.md
Feedback #3105 (EDU-10202) noted that some users with stores built on Legacy CMS Portal may misunderstand and assume compatibility with this app. This PR aims to address this issue by providing clarity and avoiding any confusion for these users.
=> Feedback #3105 - Improvement Google Tag Manager 

docs/guides/Integration-Guides/search-integration-guide/external-search-provider-specification.md
=> fix broken link

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-ppp-applied-to-pos.md
PR created to update VTEX Sales App references (EDU-10362).
=> Update VTEX Sales App reference

docs/guides/Integration-Guides/erp-integration-guide/webservice-deprecated.md
[EDU-9964](https://vtex-dev.atlassian.net/browse/EDU-9964)
[EDU-9964]: https://vtex-dev.atlassian.net/browse/EDU-9964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add webservice guide file link

docs/guides/Getting-Started/getting-started/marketplace-overview.md, docs/guides/Getting-Started/marketplace-guide.md
New guide of marketplace for developers.
=> EDU-7868 | Overview Marketplace Guide

docs/vtex-io/Store-Framework-Apps/functional-apps/affiliates-program-app.md
L 184 - L290
Removing spaces in code.
=> Fix affiliates program error log

docs/vtex-io/Store-Framework-Apps/vtex-b2b-suite/vtex-b2b-organizations.md
=> EDU-9868 inclusion of a phrase in the topic impersonate users

docs/release-notes/gift-card-support-multi-currencies.md
Release Notes - Gift card support multi-currencies (EDU-10020)
=> Release Notes - Gift card support multi-currencies

docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-preparing-your-app-distribution.md
Removes <> from URLs (probably should not be there, looks confusing on the example) and make example a valid JSON so it can be copied without reformatting
Make it clearer that metrics are optional if your app is free
=> [suggestion] Make some points clearer and example a valid JSON

docs/release-notes/2023-07-31-improved-headless-cms-plugin.md
New release notes for **Headless CMS Plugin v1.0.8: Improved sync command**
PR w/ the `navigation.json` updated: https://github.com/vtexdocs/dev-portal-content/pull/618
=> New release notes: Headless CMS Plugin v1.0.8

docs/guides/Integration-Guides/payments-integration-guide/layout-development-guide-for-payment-methods-in-smart-checkout-vtex.md
PR created to add a new calllout to the article: _Layout Development Guide for payment methods in Smart Checkout VTEX_ (EDU-10415)
=> New callout Layout Development Guide

docs/guides/Payments/payments-configuration-guides/setting-up-merchant-id-in-apple-pay.md
PR created to update reference link (EDU-10516).
=> Update Guide Setting up Merchant ID in Apple Pay

docs/release-notes/2023-07-05-recaptcha-validation-will-now-follow-orderform-configuration-for-all-requests.md
=> Update recaptcha validation configuration release note

docs/guides/Integration-Guides/recaptcha/implementing-recaptcha-in-integrations.md
=> fix step in implementing-recaptcha-in-integrations.md

docs/guides/Infrastructure/store-availability/how-to-load-test-a-store.md
=> add information about emails on how to load test a store

docs/vtex-io/App-Guides/ab-tests/vtex-io-documentation-performing-ab-testing-between-legacy-and-io.md, docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-deprecating-an-app.md, docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-running-io-scripts-in-non-io-vtex-stores.md, docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-developing-an-app.md, docs/vtex-io/Hello/contributing.md, docs/vtex-io/Perks/troubleshooting/production.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-routes.md, docs/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-debugging-performance-issues.md, docs/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-safely-enabling-performance-settings.md, docs/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-creating-a-black-friday-page-from-template.md, docs/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-rendering-a-badge.md, docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md, docs/vtex-io/Storefront-Guides/pages/vtex-io-documentation-associating-a-custom-page-to-a-content-type.md, docs/vtex-io/Storefront-Guides/vtex-io-cross-border-stores/vtex-io-documentation-creating-robots-files-for-cross-border-stores.md, docs/vtex-io/Storefront-Guides/vtex-io-documentation-enabling-the-stores-pwa-notice.md
=> fix: admin paths and typos

docs/guides/Orders/order-canceling-improvements-beta.md
=> Quick fix cancel order

docs/guides/Checkout/features/enable-the-region-for-skus.md
=> EDU-9705 add new JSON example

docs/guides/Integration-Guides/headless-commerce/headless-catalog.md
=> fix markdown - headless guide

docs/guides/Master-Data/getting-started-1/master-data-v2-basics.md
=> master data v2 basics - fix links

docs/guides/Integration-Guides/payments-integration-guide/integrating-a-new-payment-provider-on-vtex.md
PR created to publish the new article: ​​Integrating a new payment provider on VTEX (EDU-9951).
Note: Content previously reviewed by Bruno and translated by the localization team.
=> New article Integrating new payment provider

docs/guides/Master-Data/getting-started-1/setting-up-triggers-in-master-data-v2.md
=> fix search documents link

docs/guides/Integration-Guides/payments-integration-guide.md
PR created to update the Payments Integration Guides page (EDU-10633)
=> Update Payments Integration Guide page

docs/guides/Integration-Guides/data-privacy/data-residency.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture-specifications.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture.md, docs/guides/Integration-Guides/data-privacy/profile-system.md
=> fix pii guides

docs/guides/Integration-Guides/recaptcha.md, docs/guides/Integration-Guides/recaptcha/applicable-cases.md, docs/guides/Integration-Guides/recaptcha/implementing-recaptcha-in-integrations.md, docs/release-notes/2023-06-28-recaptcha-v3-support-available-for-integrations.md
Updating our reCAPTCHA docs to reflect that:
- We use reCAPTCHA enterprise.
- Checkbox validation is equivalent to reCAPTCHA v2.
- Score-based validation is equivalent to reCAPTCHA v3.
=> [EDU-10584] Update recaptcha terminology

docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-setting-your-apps-billing-model.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-billing-options.md
=> Improve price definition for setting app's billing model and billing options

docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-releasing-a-new-app-version.md
=> Improve text for IO apps release versions

docs/guides/Getting-Started/orders-overview.md
Inserted a callout about new data policy
=> add information about new data policy

docs/guides/Integration-Guides/data-privacy/changes-in-vtex-features-behavior-to-handle-pii-data.md, docs/guides/Integration-Guides/data-privacy/data-residency.md, docs/guides/Integration-Guides/data-privacy/limitations-of-the-pii-data-architecture-during-closed-beta.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture-specifications.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture.md, docs/guides/Integration-Guides/data-privacy/profile-system.md
=> adjust PII guides content

docs/guides/Integration-Guides/data-privacy/data-residency.md, docs/guides/Integration-Guides/data-privacy/limitations-of-the-pii-data-architecture-during-closed-beta.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture-specifications.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture.md, docs/guides/Integration-Guides/data-privacy/profile-system.md
=> Add seeAlso to PII guides

README.md
=> update seeAlso description on README.md

docs/release-notes/2023-09-06-fixed-headless-cms-plugin.md
PR updating the `naviagtion.json`: https://github.com/vtexdocs/devportal/pull/480
=> Add: Headless CMS release note - Bug fix for sync error 

docs/guides/Integration-Guides/login-integration-guide/registering-credentials-to-set-up-apple-id-login.md
=> fix images extension on apple credentials guide

docs/guides/Fulfillment/vtex-shipping-network/vtex-shipping-network-labels-integration.md
Make the doc public and add the link of a new article.
=> Make vtex shipping network labels integration public

docs/guides/Checkout/white-label-sellers-selection-algorithm/update-an-account-orderform-configuration.md, docs/release-notes/2023-09-12-new-checkout-settings-for-bot-attack-protection.md
=> EDU-10497 New Checkout Settings for Bot Attack Protection

docs/release-notes/apps-and-payment-connector-homologation-freeze-in-preparation-for-black-friday-2023.md
PR created to publish the new Release Notes "Apps and payment connectorPayment connector and apps homologation freeze in preparation for Black Friday 2023" (EDU-10784)
=> New Release Notes - Homologation Freeze BF

docs/release-notes/payment-connector-homologation-freeze-in-preparation-for-black-friday.md
=> Update Title BF 2022

docs/vtex-io/Getting-Started/back-end-development-guides/vtex-io-documentation-developing-service-configuration-apps.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-service.md
=> improve: wip-services docs

docs/vtex-io/Perks/troubleshooting.md
=> improve: troubleshooting

docs/vtex-io/Reference/concepts/vtex-io-documentation-clients.md
=> improve: clients

docs/vtex-io/Getting-Started/back-end-development-guides/using-node-clients.md, docs/vtex-io/Getting-Started/back-end-development-guides/vtex-io-documentation-how-to-create-and-use-clients.md, docs/vtex-io/Reference/concepts/vtex-io-documentation-clients.md
=> improve: wip work - Clients

docs/guides/Integration-Guides/payments-integration-guide/how-the-integration-protocol-between-vtex-and-antifraud-companies-works.md
PR created to add GitHub template information for the Antifraud Provider Protocol. (EDU-10786)
=> Add GitHub Antifraud Provider Protocol tempt info

docs/vtex-io/Store-Framework-Apps/advanced-components/vtex-store-icons-iconpack.md
Relacionado a EDU-10252. Próximo passo: deixar a doc visível no menu lateral
=> EDU-10252 - Update vtex-store-icons-iconpack.md

docs/release-notes/2023-10-11-faststore-v1-abandoned-cart.md
The `navigation.json` is being updated in the in [this devportal PR](https://github.com/vtexdocs/devportal/pull/506).
=> EDU-10878: FastStore v1 release note: fixed abandoned cart tracking

docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack.md
=> [EDU-10895] Feedback - pick and pack

docs/guides/Master-Data/master-data-how-it-works/master-data-schema-lifecycle.md
=> Fix link in master-data-schema-lifecycle.md

docs/guides/Integration-Guides/payments-integration-guide/google-pay-processing-information-for-payment-providers-and-anti-fraud.md
=> Fix Google Pay - DPAN field names 

docs/release-notes/new-referencevalue-parameter-create-payment-endpoint.md
PR created to publish the Release Notes "New referenceValue parameter in the Create Payment endpoint request body" (EDU-10947)
=> New referenceValue parameter Create Payment edpt

docs/guides/Integration-Guides/tax-service-integration-guide/tax-services-specification.md
=> EDU-10771 Fix JSON Error

docs/guides/Integration-Guides/gift-card-integration-guide.md
PR created to update the Gift card integration guide page.
=> Update Gift card integration guide page

docs/release-notes/2023-11-17-temporary-freeze-on-automatic-app-distribution-in-preparation-for-black-friday-2023.md
=> test: new release type

docs/guides/Integration-Guides/data-privacy/pii-data-architecture.md, docs/guides/Integration-Guides/data-privacy/profile-system.md, docs/guides/Integration-Guides/data-privacy/working-with-schemas-in-the-profile-system.md
=> Add profile system schemas guide

docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack-carriers-integration-protocol.md, docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack-get-order-status-and-information-api.md, docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack.md, docs/guides/Getting-Started/authentication/api-authentication-using-application-keys.md, docs/guides/Getting-Started/authentication/app-authentication-using-auth-tokens.md, docs/guides/Getting-Started/authentication/authentication.md, docs/guides/Getting-Started/authentication/checking-which-user-is-currently-authenticated.md, docs/guides/Getting-Started/authentication/expiring-a-shoppers-password.md
=> fix: seeAlso usage

docs/guides/CMS/cms-api-overview.md, docs/guides/Checkout/cart-attachments-section-quick-start-guides/add-customer-preferences-to-the-cart.md, docs/guides/Checkout/customization/change-payment-method-names-in-checkout.md, docs/guides/Checkout/customization/checkout-customization-guide.md, docs/guides/Checkout/customization/customize-checkout-confirmation-pages.md, docs/guides/Checkout/features/enable-the-save-user-data-opt-in.md, docs/guides/Checkout/how-to-use-the-change-seller-feature.md, docs/guides/Checkout/orders-2/create-a-regular-order-using-the-checkout-api.md, docs/guides/Checkout/security/ssltls-security-protocols-and-ciphers-at-checkout.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/get-cart-installments-information.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/ignore-profile-data.md, docs/guides/Checkout/white-label-sellers-selection-algorithm.md, docs/guides/Checkout/white-label-sellers-selection-algorithm/get-and-update-the-seller-exchange-window.md, docs/guides/Fulfillment/multilevel-omnichannel-inventory/multilevel-omnichannel- inventory-api-integration.md, docs/guides/Fulfillment/multilevel-omnichannel-inventory/multilevel-omnichannel-inventory.md, docs/guides/Fulfillment/vtex-shipping-network/tracking-1.md, docs/guides/Getting-Started/marketplace-api.md, docs/guides/Integration-Guides/api-guides/setting-up-the-spf.md, docs/guides/Integration-Guides/catalog-integration/images.md, docs/guides/Integration-Guides/catalog-integration/product-specifications.md, docs/guides/Integration-Guides/catalog-integration/sku-specifications.md, docs/guides/Integration-Guides/external-marketplace-integration-guide/deprecated-how-to-collect-orders-from-sales-channels.md, docs/guides/Integration-Guides/external-marketplace-integration-guide/deprecated-order-logs.md
=> fix: replace callout magic blocks

docs/guides/Integration-Guides/erp-integration-guide/erp-integration-import-prices.md, docs/vtex-io/App-Guides/ab-tests/vtex-io-documentation-running-native-ab-testing.md, docs/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-listmigration.md
=> fix: backtick

docs/guides/Checkout/features/configure-the-global-checkout.md, docs/guides/Fulfillment/multilevel-omnichannel-inventory/multilevel-omnichannel- inventory-api-integration.md, docs/guides/Integration-Guides/api-guides.md, docs/guides/Message-Center/templates/including-order-variables-in-the-transactional-email-template.md, docs/guides/UI-Customization/my-account/ui-customization-my-authentication.md, docs/guides/VTEX-Sales-App/how-to-customize-vtex-sales-app/change-vtex-sales-app-language.md, docs/guides/VTEX-Sales-App/how-to-customize-vtex-sales-app/enable-cart-transfer-between-devices.md, docs/guides/VTEX-Sales-App/how-to-customize-vtex-sales-app/enable-order-filter-by-sales-associate.md, docs/guides/VTEX-Sales-App/how-to-customize-vtex-sales-app/enable-the-remarks-field-in-the-order-screen.md, docs/guides/VTEX-Sales-App/how-to-customize-vtex-sales-app/force-stock-availability.md
=> fix: md errors

docs/guides/Integration-Guides/login-integration-guide/login-integration-guide-admin-saml2.md
=> EDU-11133 - Fix image in SAML guide

docs/guides/Getting-Started/api-response-codes.md, docs/guides/Getting-Started/best-practices-for-avoiding-rate-limit-errors.md, docs/guides/Getting-Started/handling-errors-and-exceptions.md, docs/guides/Getting-Started/tests.md
=> feat: add api-response-codes and +

docs/guides/Getting-Started/api-response-codes.md, docs/guides/Getting-Started/best-practices-for-avoiding-rate-limit-errors.md, docs/guides/Getting-Started/handling-errors-and-exceptions.md
=> fix: frontmatter

docs/guides/Pricing-Hub/pricing-hub-overview.md, navigation.json
=> [EDU-11185] Fixed URL

docs/guides/Master-Data/getting-started-1/setting-up-triggers-in-master-data-v2.md
=> EDU-11057 - Edit conditions information - Master Data v2

docs/release-notes/extensions-hub-our-new-place-to-promote-apps-and-partners-inside-vtex-admin.md, docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-becoming-a-registered-vtex-app-store-developer.md, docs/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-submitting-your-app-in-the-vtex-app-store.md
=> Add callouts about App Store restrictions

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md
Update callout information - BillingOptions field
PR created to update callout information - BillingOptions field (Payment Provider Framework)
=> Update callout information - BillingOptions field

docs/vtex-io/Store-Framework-Apps/functional-apps/vtex-store-sitemap.md
=> sitemap guide - fix markdown and adjust response description

docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-workspace-behavior-with-app-installations.md, docs/vtex-io/App-Guides/vtex-io-documentation-making-your-new-app-version-publicly-available/vtex-io-documentation-promoting-a-workspace-to-master.md
=> Workspace behavior with app installations

docs/vtex-io/Store-Framework-Apps/vtex-b2b-suite/vtex-b2b-organizations.md
=> [EDU-10865] Added information impersonate users

docs/guides/Checkout/creating-a-regular-order-from-an-existing-cart.mdx, docs/guides/Checkout/orders-2/create-a-regular-order-from-an-existing-cart.md
=> feat: creating-a-regular-order-from-an-existing-cart

docs/vtex-io/services/developing-services-on-vtex-io.mdx, docs/vtex-io/services/services-1-getting-started-with-the-boilerplate.mdx, docs/vtex-io/services/services-2-handling-and-receiving-events.mdx, docs/vtex-io/services/services-3-using-the-analytics-client.mdx, docs/vtex-io/services/services-4-using-events-as-triggers.mdx, docs/vtex-io/services/services-5-using-the-master-data-client.mdx, docs/vtex-io/services/services-6-graphql-retrieving-data-from-master-data.mdx, docs/vtex-io/services/services-7-using-graphiql.mdx, docs/vtex-io/services/services-conclusion.mdx
=> 23h2kr4 add services tutorial codehike

docs/guides/Catalog/managing-products.mdx, docs/guides/Integration-Guides/catalog-integration/products.md
=> feat: managing-products

docs/guides/Getting-Started/getting-started/getting-started.md
=> Update getting-started (fix account management link)

docs/guides/Orders/orders-feed.md
Adding a section about good practices in orders integrations, solving some feedbacks and correcting markdown errors.
=> Best practices for integrations

docs/vtex-io/Reference/concepts/vtex-io-documentation-workspace.md
=> Doc: updating vtex-io-documentation-workspace.md

docs/vtex-io/Store-Framework-Apps/regionalization-beta.md
[EDU-10002](https://vtex-dev.atlassian.net/browse/EDU-10002)
[EDU-10002]: https://vtex-dev.atlassian.net/browse/EDU-10002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update regionalization (beta) guide

docs/vtex-io/App-Guides/ab-tests/vtex-io-documentation-running-native-ab-testing.md
=> Doc: Updating vtex-io-documentation-running-native-ab-testing.md

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md
PR created to add information about updating connector settings and making updates to the article (EDU-11176).
=> Add information about updating connector settings PPF

docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store.md, docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md, docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-engineering-guidelines.md
=> Fix: Documentation guidelines

docs/guides/Integration-Guides/data-privacy/profile-system.md
=> profile system - remove events not available in audit yet

docs/guides/Composability/vtex-composable-and-complete.md
Improved markdown syntax, and edited structure of text
=> fix markdown 

docs/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-2-prerequesites.md
The information about the differences in installing the 3.x or 5.x version of the Edition App was added.
=> Doc: updating vtex-io-documentation-2-prerequesites.md

docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-app-template.md
Removing references to Offer Management from the App Template doc.
=> EDU-11493| sunset offer management

docs/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-3-creating-the-new-app.md
- Adjustments to be in accordance with editorial guidelines.
- Step 3 (linking the app) has been added.
- Callout about `yarn` command when linking the app
=> Doc: Updating vtex-io-documentation-3-creating-the-new-app.md

docs/vtex-io/Reference/concepts/vtex-io-documentation-edition-app.md
Differences between Edition Store app versions have been added to the documentation.
=> Doc: Improving vtex-io-documentation-edition-app.md

docs/faststore/components/organisms/filter-slider.mdx, docs/faststore/components/organisms/navbar.mdx
=> update: navbar frontmatter

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-app.md
Update callout (EDU-10976)
PR created to improve transactionValidation.vtex information (EDU-10976).
=> Update callout information (Payment App)

docs/guides/Integration-Guides/catalog-integration/sku-specifications.md
Updated FieldvalueId informations (requirements).
=> Update sku-specifications.md (fieldvalueid)

docs/vtex-io/Storefront-Guides/google-tag-manager/vtex-io-documentation-setting-up-google-tag-manager.md
Fixing "See Also" section link about the search analytics.
=> EDU-9909 Feedback #3006 - Improvement

docs/faststore/components/organisms/newsletter.mdx
Adds Newsletter from `@faststore/ui` component doc
=> docs: Adds Newsletter doc

docs/faststore/docs/headless-cms/overview.mdx
The content is also being updated in the faststore.dev portal: https://github.com/vtex/faststore/pull/2234
=> Add: Headless CMS user permission 

docs/faststore/docs/headless-cms/2-setting-up-the-headless-cms.mdx
Fixed links and documentation typos.
=> Headless CMS: fix links and typos

docs/vtex-io/Getting-Started/back-end-development-guides/how-to-receive-catalog-changes-on-vtex-io.md
[EDU-11629](https://vtex-dev.atlassian.net/browse/EDU-11629)
[EDU-11629]: https://vtex-dev.atlassian.net/browse/EDU-11629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> edit broadcaster app mentions

docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-workspaces-best-practices.md
=> Doc: Creating vtex-io-documentation-workspaces-best-practices.md

docs/guides/Search/access-control-list.md, docs/guides/Search/vtex-io-documentation-segmenting-the-search-result.md
=> [EDU-11752] Reactivate docs

docs/faststore/components/getting-started.mdx, docs/faststore/docs/api-extensions/extending-api-schema.mdx, docs/faststore/docs/api-extensions/extending-queries-using-fragments.mdx, docs/faststore/docs/customization/api-extensions/extending-api-schema.mdx, docs/faststore/docs/customization/api-extensions/overview.mdx, docs/faststore/docs/customization/api-extensions/troubleshooting.mdx, docs/faststore/docs/customization/using-themes/components.mdx, docs/faststore/docs/customization/using-themes/overview.mdx, docs/faststore/docs/getting-started/glossary.mdx, docs/faststore/docs/getting-started/requirements.mdx, docs/faststore/docs/global-tokens/global-tokens-overview.mdx, docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx, docs/faststore/docs/reference/global-tokens/overview.mdx, docs/faststore/docs/reference/themes/overview.mdx
=> fix: broken links

docs/release-notes/2024-02-23-onboarding-guide.md
I'm updating the `navigation.json` in the [597 PR](https://github.com/vtexdocs/devportal/pull/597)
=> Release note: Onboarding guide

docs/faststore/docs/getting-started/4-next-steps.mdx
=> Chore: fix Faststore docs

docs/guides/VTEX-Shipping-Network/vtex-shipping-network-api-overview.md
=> Fix broken links

docs/vtex-io/App-Guides/managing-edition-apps/seller-portal-edition-app.md
=> EDU-11810| Update seller-portal-edition-app.md

docs/release-notes/2024-06-08-faststore-content-in-the-developer-portal.md
Reference: https://github.com/vtexdocs/devportal/pull/608/files
=> EDU-11667 - Release note - FastStore content migration

docs/guides/Getting-Started/getting-started/making-your-first-request.md
updating the download process through postman
=> EDU11345 | Update making your first request

docs/vtex-io/Getting-Started/back-end-development-guides/vtex-io-documentation-developing-service-configuration-apps.md
=> Add policy for service app to read configuration

docs/guides/Catalog-Seller-Portal/catalog-api-seller-portal-overview.md
=> EDU-11079-fix-seller-account-info

docs/release-notes/2024-03-19-new-field-isMarketplaceResponsibleForTaxes-checkout-api.md
=> feat: add release note isMarketplaceResponsibleForTaxes

docs/vtex-io/Reference/concepts/vtex-io-documentation-policies/vtex-io-documentation-policies-from-license-manager.md
=> VTEX IO policies from License Manager

docs/faststore/docs/headless-cms/multiple-page-template.mdx
PR that updates the `navigation.json`: https://github.com/vtexdocs/devportal/pull/614
=> EDU-11715: Multiple page templates

docs/vtex-io/App-Guides/configuring-workspaces/vtex-io-documentation-workspaces-best-practices.md
Updating the document according to Localization review.
Updating the document according to Localization review.
=> Doc: Update vtex-io-documentation-workspaces-best-practices.md

docs/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-docs-builder.md
=> Doc; Creating vtex-io-documentation-docs-builder.md

docs/faststore/docs/getting-started/requirements.mdx
=> Quick win: FastStore Onboarding broken link

docs/release-notes/2024-04-10-multiple-page-template.md
=> Fix Multiple page templates release note

docs/guides/Payments/payments-configuration-guides/metadata-information-in-payment-transactions.md
PR created to publish the new article "Metadata information in payment transactions" using as a basis the Release Note: "New fields available for sending metadata in payment flow routes" (EDU-12224).
=> New article Metadata information in payment transactions

docs/guides/Payments/payments-configuration-guides.md
PR created to update payment configuration article table.
=> Update payment configuration article table

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-secure-proxy.md, docs/release-notes/secure-proxy-custom-tokens-base64-encoding-method-is-now-available.md
PR created to publish the new Release Note "Secure Proxy custom tokens: Base64 encoding method is now available" and update the article "Secure Proxy". (EDU-12188).
=> Release Note Secure proxy custom tokens base64

README.md, docs/guide_template.md, docs/release_notes_template.md
=> Update templates and guidelines

docs/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-docs-builder.md
=> Doc: Updating vtex-io-documentation-docs-builder.md

docs/faststore/docs/headless-cms/multiple-page-template.mdx
This PR adds a "Before you begin" section. This section explains the steps to update your core package and synchronize the hCMS updates before using the templates.
=> Fix: Multiple page template

docs/guides/B2B-Suite/b2b-organizations/bulk-import-buyer-organizations-spreadsheet.md, docs/guides/B2B-Suite/b2b-organizations/bulk-import-spreadsheet.md
=> [EDU-10740] Bulk Import Spreadsheet Guide

docs/vtex-io/Reference/concepts/vtex-io-documentation-service.md
=> Service configuration and best practices

docs/guides/Getting-Started/search-overview.md
[EDU-11084](https://vtex-dev.atlassian.net/browse/EDU-11084)
[EDU-11084]: https://vtex-dev.atlassian.net/browse/EDU-11084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix legacy search info in search overview

docs/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-styles-builder.md
=> Creating vtex-io-documentation-styles-builder.md

docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx
This PR updates the [Step 2 - Configuring the Headless CMS](https://developers.vtex.com/docs/guides/faststore/headless-cms-1-configuring-the-vtex-account#step-2-configuring-the-headless-cms) to reflect the new interface due to the Project feature.
Reference: EDU-12346
=> Quick win: fix CMS settings reference

docs/guides/Master-Data/v1-guides.md
=> fix master data links

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-assets-builder.md
=> Creating vtex-io-documentation-assets-builder.md

docs/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-store-builder.md
=> Creating vtex-io-documentation-store-builder.md

crowdin.yml
Adicionar o arquivo de configuração do Crowdin para testarmos a integração entre o Crowdin e o GitHub.
=> add crowdin configuration file

docs/localization/en_vtex-tracking.md
Teste adicionando um arquivo com o prefixo en.
=> add file with locale prefix

docs/faststore/docs/customization/building-sections/overrides/component-props.mdx, docs/faststore/docs/customization/building-sections/overview.mdx
=> Quick win: fix Section override doc issues

docs/faststore/docs/headless-cms/3-adding-content-types-and-sections.mdx, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/change-price.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/get-cart-information-by-id.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/get-cart-installments-information.md, docs/guides/Checkout/shopping-cart-section-api-quick-start-guides/remove-all-personal-data.md, docs/guides/Fulfillment/vtex-shipping-network/vtex-shipping-network-labels-integration.md, docs/guides/Integration-Guides/payments-integration-guide/payments-integration-implementing-a-payment-provider.md, docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md, docs/guides/Integration-Guides/payments-integration-guide/payments-integration-purchase-flows.md, docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-creating-a-custom-search-results-page.md, docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-enabling-404-pages.md, docs/release-notes/addition-of-signature-parameter-on-callback-url-for-payment-integrations.md
=> grammar fixes

docs/faststore/docs/go-live/2-configuring-external-dns.mdx
This PR updates the screenshot from [step 3](https://developers.vtex.com/docs/guides/faststore/go-live-2-configuring-external-dns#step-3-configuring-domains-in-vtex-account-settings) and also adds a callout about adding `www.` domain and subdomains without `www.` to guarantee the checkout will work.
Reference: [EDU-12122](https://vtex-dev.atlassian.net/browse/EDU-12122)
[EDU-12122]: https://vtex-dev.atlassian.net/browse/EDU-12122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12122: Update part 2 from the FastStore go live

docs/guides/Integration-Guides/data-privacy/changes-in-vtex-features-behavior-to-handle-pii-data.md, docs/guides/Integration-Guides/data-privacy/data-protection-plus.md, docs/guides/Integration-Guides/data-privacy/data-residency.md, docs/guides/Integration-Guides/data-privacy/erasing-customer-data.md, docs/guides/Integration-Guides/data-privacy/limitations-of-the-pii-data-architecture-during-closed-beta.md, docs/guides/Integration-Guides/data-privacy/pii-data-architecture-specifications.md, docs/guides/Integration-Guides/data-privacy/profile-system.md, docs/guides/Integration-Guides/data-privacy/working-with-schemas-in-the-profile-system.md
=> Update PII guides with Data Protection Plus

docs/faststore/docs/go-live/2-configuring-external-dns.mdx
This PR aims to reinforce the correct domains information in License Manager and it became a nice-to-have note after an incident in a FS store's go-live process.
=> EDU-12469 | feat: Add note regarding custom prefixes when configuring domains in LM

docs/faststore/docs/headless-cms/multiple-page-template.mdx
This PR aims to add docs regarding how to use the rewrites feature along with the Multiple page templates in PLP for FastStore.
FastStore PR
- https://github.com/vtex/faststore/pull/2320
=> Feat: multiple templates rewrites plp

docs/release-notes/2024-05-27-changes-in-authentication-requirements-for-external-gift-card-providers.md
Update Release Note type information.
=> Update Release Note type information

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-site-editor.md, docs/guides/vtex-io/Storefront-Guides/vtex-io-documentation-going-live/vtex-io-documentation-migrating-storefront-from-legacy-to-io.md
Baseado [neste PR](https://github.com/vtexdocs/devportal/pull/664#pullrequestreview-2083578954), percebi alguns links redirecionando para docs incorretas.
=> Quick win: Fix links

docs/guides/VTEX-Platform-Overview/Cloud-infrastructure/cloud-infrastructure.md
=> 24H1KR3: Cloud infrastructure - fix image links

docs/guides/VTEX-Platform-Overview/Store-architecture/understanding-vtex-reference-architectures.md
The links to the Composability and Extensibility guides have been deleted while the documentation is being prepared, in order to avoid broken links.
=> EDU-12305 - Understanding reference architectures - deleting broken links

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-building-a-shelf.md
[EDU-10762](https://vtex-dev.atlassian.net/browse/EDU-10762)
[EDU-10762]: https://vtex-dev.atlassian.net/browse/EDU-10762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-10762 - Updating Building a Shelf doc

docs/guides/VTEX-Platform-Overview/Data-privacy/data-privacy.md
=> 24H1KR3: Data privacy - fix image extension

docs/guides/VTEX-Platform-Overview/security.md
=> 24H1KR3: security - fix mermaid diagram

docs/guides/VTEX-Platform-Overview/vtex-platform-overview.md
[EDU-11962](https://vtex-dev.atlassian.net/browse/EDU-11962)
[EDU-11962]: https://vtex-dev.atlassian.net/browse/EDU-11962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 24H1KR3: VTEX Platform Overview category cover

docs/guides/VTEX-Platform-Overview/developer-experience.md
The following changes were made:
- Links to the onboarding documentation for SF and FastStore were removed from the `seeAlso`.
- An incorrect information in the topic about A/B tests was corrected.
- The paragraph about CI/CD was removed to be reinserted later with the correct information.
=> Doc: Fixing developer-experience.md

docs/guides/Fulfillment/multilevel-omnichannel-inventory/multilevel-omnichannel-inventory.md
[EDU-12650](https://vtex-dev.atlassian.net/browse/EDU-12650)
[EDU-12650]: https://vtex-dev.atlassian.net/browse/EDU-12650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix broken link and formatting in multilevel-omnichannel-inventory.md

docs/guides/VTEX-Platform-Overview/Composability/vtex-composable-components.md
defining column min-width to prevent column text from breaking
=> edit composability tables

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-node-builder.md
=> fixing indentation node builder

docs/faststore/docs/customization/building-sections/list-of-native-sections.mdx
Reference: [EDU-12409](https://vtex-dev.atlassian.net/browse/EDU-12409)
[EDU-12409]: https://vtex-dev.atlassian.net/browse/EDU-12409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Quick win: Update native section link

docs/release-notes/2024-06-06-deprecation-of-vtex-order-sms-notification.md
=> Fixing date in the release note

docs/guides/vtex-io/Getting-Started/back-end-development-guides/configuring-dynamic-routes-in-vtex-io-services.md
[EDU-11950](https://vtex-dev.atlassian.net/browse/EDU-11950)
[EDU-11950]: https://vtex-dev.atlassian.net/browse/EDU-11950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: EDU-11950 - configuring-dynamic-routes-in-vtex-io-services.md

docs/faststore/docs/what-is-faststore.mdx, docs/guides/faststore/what-is-faststore.md
=> Feat: Update FastStore overview

docs/guides/faststore/faststore.md
=> Fix: typos and subtitles

docs/guides/Master-Data/v1-guides/search-and-scroll-api-queries.md
[EDU-12192](https://vtex-dev.atlassian.net/browse/EDU-12192)
[EDU-12192]: https://vtex-dev.atlassian.net/browse/EDU-12192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add callout with scroll limitations

docs/faststore/docs/customization/using-themes/components.mdx
=> Fix: typos and broken links

docs/guides/Integration-Guides/erp-integration-guide/change-seller.md
Correcting links and markdown.
=> Feedback change seller

docs/guides/Integration-Guides/customer-credit-integration-guide.md
=> Customer Credit Integration Guide Landing page

docs/faststore/docs/managing-performance/testing-the-server-side-rendering.md
FastStore migration - [EDU-12635](https://vtex-dev.atlassian.net/browse/EDU-12635)
[EDU-12635]: https://vtex-dev.atlassian.net/browse/EDU-12635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12635 - Creating testing-the-server-side-rendering.md

docs/troubleshooting/development/i-cannot-install-vtex-io-cli.md
=> Doc: Fixing images URLs in i-cannot-install-vtex-io-cli.md

docs/guides/VTEX-Platform-Overview/Cloud-infrastructure/cloud-infrastructure.md
[EDU-12780](https://vtex-dev.atlassian.net/browse/EDU-12780)
[EDU-12780]: https://vtex-dev.atlassian.net/browse/EDU-12780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cloud infrastructure - remove details about providers

docs/release-notes/2024-06-13-new-logistics-api-endpoints-to-update-inventory-lead-time-and-quantity.md
Release note for two new endpoints in Logistics API.
=> New inventory endpoints release note

docs/guides/Getting-Started/checkout-overview.md, docs/guides/Getting-Started/orders-overview.md, docs/guides/Getting-Started/subscriptions.md, docs/guides/Master-Data/master-data-how-it-works/master-data-components.md
=> add data privacy callouts

docs/faststore/docs/customization/building-sections/list-of-native-sections.mdx
=> Add: Headless CMS schemas available for each section

docs/guides/Payments/payments-configuration-guides/setting-up-merchant-id-in-apple-pay.md
PR created to fix reference link (EDU-12718).
=> Fix reference link info

docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-managing-url-redirects.md
[EDU-12681](https://vtex-dev.atlassian.net/browse/EDU-12681)
Adding the information that is not possible to create redirects using wildcard or variables.
[EDU-12681]: https://vtex-dev.atlassian.net/browse/EDU-12681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc: Updating Managing URL redirects

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx, docs/faststore/docs/getting-started/1-onboarding/overview.mdx, docs/faststore/docs/getting-started/1-onboarding/starting-the-project.mdx, docs/faststore/docs/getting-started/overview.mdx, docs/faststore/docs/getting-started/requirements.mdx
PR to update the onboarding documentation according to the team's review for FastStore WebOps.
P.S.: The sidebar will be updated in the following PR: https://github.com/vtexdocs/devportal/pull/635
=> Feat: Update: Getting started - FastStore WebOps app

docs/guides/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-creating-an-interface-for-your-app-settings.md
[EDU-5808](https://vtex-dev.atlassian.net/browse/EDU-5808) 
[EDU-5808]: https://vtex-dev.atlassian.net/browse/EDU-5808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc: Creating vtex-io-documentation-creating-an-interface-for-your-app-settings.md

docs/guides/Orders/orders-feed.md
Improving a description and fixing some markdown issues.
=> Add sentence to feed guide

docs/troubleshooting/development/i-cant-install-vtex-io-cli.md, docs/troubleshooting/store-performance/i-cant-complete-a-purchase-on-a-faststore-website.md
Updates in the sidebar: https://github.com/vtexdocs/devportal/pull/695
=> Fix troubleshooting docs title

docs/troubleshooting/development/development-overview.md, docs/troubleshooting/store-performance/store-performance-overview.md
=> Feat: add troubleshooting dev and store performance overview

docs/faststore/docs/api-extensions/consuming-api-extensions.mdx, docs/faststore/docs/api-extensions/extending-api-schema.mdx, docs/faststore/docs/api-extensions/extending-queries-using-fragments.mdx, docs/faststore/docs/api-extensions/troubleshooting.mdx, docs/faststore/docs/customization/api-extensions/consuming-api-extensions.mdx, docs/faststore/docs/customization/api-extensions/extending-queries-using-fragments.mdx, docs/faststore/docs/customization/api-extensions/overview.mdx, docs/faststore/docs/customization/api-extensions/troubleshooting.mdx, docs/faststore/docs/faststore-api/overview.mdx
=> Update: FastStore API

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-components.md
[EDU-11381](https://vtex-dev.atlassian.net/browse/EDU-11381)
[EDU-11381]: https://vtex-dev.atlassian.net/browse/EDU-11381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc: Creating vtex-io-documentation-components.md

docs/troubleshooting/overview.md
=> fix: troubleshooting typo

docs/faststore/docs/api-extensions/best-practices.mdx, docs/faststore/docs/reference/project-structure/updating-the-core-package-version.mdx
Jira task: [EDU-11542](https://vtex-dev.atlassian.net/browse/EDU-11542)
[EDU-11542]: https://vtex-dev.atlassian.net/browse/EDU-11542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-11542: New API extension improvements

docs/guides/VTEX-Platform-Overview/vtex-platform-overview.md
=> 24H1KR3: VTEX Platform Overview - apply localization review

docs/guides/vtex-io/Reference/vtex-io-documentation-vtex-io-cli-installation-and-command-reference/vtex-io-documentation-vtex-io-cli-install.md
=> Add Xcode to IO CLI install instructions

docs/faststore/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx, docs/faststore/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
=> EDU-9991: update go live guides according to LOC review

docs/faststore/docs/headless-cms/2-setting-up-the-headless-cms.mdx
=> Fix: Tabs indentation issue

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-edition-app.md
- Callout improved
- The order of the Edition Apps were changed in the `List of native Edition Apps` section.
=> Doc: Updating vtex-io-documentation-edition-app.md

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-store-builder.md
=> Doc: Fixing vtex-io-documentation-store-builder.md

docs/faststore/docs/headless-cms/how-to-preview-changes-in-development-mode.mdx, docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
- Updating sidebar: https://github.com/vtexdocs/devportal/pull/669
- Reference: EDU-11668
=> feat: new guide for headless CMS

docs/troubleshooting/development/my-store-does-not-reflect-the-overrides-i-created.md
- Reference: EDU-11907
- Atualizando o `navigation.json` [neste PR](https://github.com/vtexdocs/devportal/pull/659/files#diff-3279d93e3d5976b83e6915c478be4293cf9013fc3306db94d256ad4477871bb9R14866-R14870).
=> Add: troubleshooting for the override feature

docs/guides/VTEX-Platform-Overview/developer-experience.md
Adding links to SeeAlso section.
[EDU-12621](https://vtex-dev.atlassian.net/browse/EDU-12621)
[EDU-12621]: https://vtex-dev.atlassian.net/browse/EDU-12621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12621 - docs: updating developer-experience.md

docs/guides/Integration-Guides/login-integration-guide/unifying-login-for-different-accounts.md
=> remove hyphen and fix markdown

docs/guides/VTEX-Platform-Overview/Cloud-infrastructure/cloud-infrastructure.md
=> apply localization review - cloud infrastructure

docs/guides/Getting-Started/payments-overview.md
=> Fix links and improve spacing between headers - Payments overview

README.md
=> Update README.md regarding removing an API

docs/guides/VTEX-Platform-Overview/security.md
=> add ISO certification to security guide

docs/localization/conversao-de-conteudo-em-markdown-e-traducao-automatica-no-github.md, docs/localization/teste-conversao-markdown.md, docs/localization/vtex-tracking.md
Reverts vtexdocs/dev-portal-content#1277
=> Revert "Remove localization files"

docs/guides/Payments/payments-configuration-guides/implementing-a-pre-analysis-antifraud-flow-for-debit-card-transactions.md
Removing a misleading paragraph. There is no need to do the mentioned checking before enabling debit card for antifraud flow.
=> docs: update debit card section

docs/guides/VTEX-Platform-Overview/store-architecture/understanding-vtex-reference-architectures.md
=> apply localization review - understanding VTEX reference architectures

docs/faststore/components/features/regionalization.mdx, docs/faststore/components/features/search.mdx, docs/faststore/components/getting-started.mdx, docs/faststore/docs/customization/building-sections/override-use-cases/overview.mdx, docs/faststore/docs/customization/building-sections/overrides/component-props.mdx, docs/faststore/docs/customization/building-sections/overrides/components-and-props-v1.mdx, docs/faststore/docs/customization/building-sections/overrides/getoverriddensection-function.mdx, docs/faststore/docs/customization/building-sections/overrides/native-component.mdx, docs/faststore/docs/customization/building-sections/overrides/overview.mdx, docs/faststore/docs/customization/using-themes/mixins-breakpoints.mdx, docs/faststore/docs/customization/using-themes/overview.mdx, docs/faststore/docs/getting-started/1-onboarding/overview.mdx, docs/faststore/docs/getting-started/1-onboarding/starting-the-project.mdx, docs/faststore/docs/getting-started/2-setting-up-the-project.mdx, docs/faststore/docs/go-live/before-you-begin.mdx, docs/faststore/docs/go-live/overview.mdx, docs/faststore/docs/headless-cms/multiple-page-template.mdx, docs/faststore/docs/headless-cms/overview.mdx, docs/faststore/docs/headless-cms/widgets.mdx, docs/faststore/docs/reference/global-tokens/overview.mdx, docs/faststore/docs/reference/project-structure/custom-cypress.mdx, docs/faststore/docs/troubleshooting/analytics-and-partytown.mdx, docs/faststore/docs/troubleshooting/tracing-the-error-source.mdx
=> (fix): faststore typos

docs/release-notes/2024-07-10-new-vtex-troubleshooting-guides.md
- Reference: EDU-11984
- Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/726
=> 24H1KR1: Troubleshooting release note

docs/faststore/docs/customization/dynamic-content/overview.mdx, docs/faststore/docs/customization/dynamic-content/step-1-setting-up-the-store-code-for-dynamic-content.mdx, docs/faststore/docs/customization/dynamic-content/step-2-handling-the-dynamic-content-in-custom-sections.mdx
PR to update the sidebar and redirects: https://github.com/vtexdocs/devportal/pull/728
=> Review: Dynamic Content guides

docs/guides/VTEX-Platform-Overview/developer-experience.md
=> apply localization review - developer experience

docs/guides/VTEX-Platform-Overview/Composability/composability.md
=> apply localization review - composability guide

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx, docs/release-notes/2024-07-10-new-vtex-troubleshooting-guides.md
=> WebOps Dashboard: Add a Live store ID section

docs/guides/VTEX-Platform-Overview/Composability/interactive-marchitecture-tool.md
=> apply localization review - interactive marchitecture tool

docs/guides/vtex-io/App-Guides/create-master-data-crud-app.md, docs/release-notes/2024-04-17-master-data-v1-calculated-field-and-change-field-value-trigger-deprecation.md
=> add info about mdv1 services guide

docs/guides/VTEX-Platform-Overview/store-architecture/store-architecture.md
=> apply localization review - store architecture

docs/release-notes/2024-07-10-new-vtex-troubleshooting-guides.md
=> chore(2024-07-10-new-vtex-troubleshooting-guides.md): adding excerpt

docs/faststore/docs/customization/building-sections/overrides/section-styles.mdx
=> EDU-13061: Fix links and typos

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-store-theme.md
[EDU-4914 - (Concept) Store Theme](https://vtex-dev.atlassian.net/browse/EDU-4914)
=> EDU-4914 - Creating Store Theme documentation

docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-a-contact-form-to-a-landing-page.mdx, docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-installment-information-in-the-product-details-page.mdx, docs/faststore/docs/api-extensions/api-extensions-use-cases/overview.mdx
Updates on the `navigation.json`: https://github.com/vtexdocs/devportal/pull/730
Codehike preview:
- Using `<CH.Scrollycoding>`:
- [Adding a contact form to a landing page](https://play.codehike.org/#N4IgtgJgHiBcIFokB0B2AXAlugNgU1gAIByAQQgk1QHNCBDQgYwHsM7H1CAzZgJzELpm9QjjqpKNQgAc61PMTRIEaNABUAFpgDOhagFdMEPIUw4c+7el510eXRuYB3QcI3iI+QhFsMuvZgEGAGFWdHZOAFVdHn56CUJtPATsVxF0LV4IBFledABPQlIABQBJADpCNWEMnUJkiAAaQicTJzMcJl48WxMQsIjCaJk5NuwNEVC2Dm4+MHLVVAA+QkBOQkB4P8IAMT5vPHCzPAhTVCtefQ5MVl1WIrL6qDtTq9Pm7q48XjSAbRLSh6e2he2gAugAKDTodDSbSwAD0cOMADc8DhmNJPtpyki7FByiwwIjmIxtHCDEZ7HCuHQrFY+Hg4XRpJgEHhHskgdcEMwUbwkZg8E4AJR6QzGBaoADEksIU1x6EWCEIAE1mPoWuJOEIuj07JMBjNhrJ5IlhNpHNIMbxdIxxEwDZx8mqvnTuhKlar1U5NWk6BQRLEBNozRarTa7UkEhk8Jgvt0AI76ezoG5fD5HABG7AA1u6qm4PF5o95fIl9BmwDpOaduAEBLUbQ7Zvxmk71ag8EcfmynsctjT …
=> EDU-12593: API extensions use cases

docs/faststore/docs/headless-cms/managing-content-with-scopes-and-requiredscopes.mdx
- Updates in the `navigation.json`: https://github.com/vtexdocs/devportal/pull/735
- To access the preview:
- Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-11632-scoped-sections) to set up the portal with this branch changes.
- Open the following link: https://developers.vtex.com/docs/guides/faststore/headless-cms-managing-content-with-scopes-and-requiredscopes
=> EDU-11632 - hCMS ‘scopes’ and ‘requiredScopes’

docs/guides/Integration-Guides/api-guides/setting-up-dkim-for-transactional-emails.md
[EDU-13075](https://vtex-dev.atlassian.net/browse/EDU-13075)
[EDU-13075]: https://vtex-dev.atlassian.net/browse/EDU-13075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix API URL on DKIM guide

docs/guides/Integration-Guides/headless-commerce/headless-catalog.md
=> Remove deprecated endpoints

docs/guides/Orders/orders-feed.md
[Feedback #4023](https://vtex-dev.atlassian.net/browse/EDU-13091)
=> Feed v3 expression tests correction

docs/guides/VTEX-Session/sessions-system-overview.md
[EDU-13103](https://vtex-dev.atlassian.net/browse/EDU-13103)
[EDU-13103]: https://vtex-dev.atlassian.net/browse/EDU-13103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix field name - session overview

docs/guides/Integration-Guides/payments-integration-guide/payment-provider-list-test.md
=> Payment list test

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-site-editor-schema-examples.mdx
=> Fixing seeAlso in the frontmatter

docs/faststore/docs/reference/project-structure/updating-the-core-package-version.mdx
=> Review "Updating the '@fastore/core' package version" doc

docs/faststore/docs/headless-cms/widgets.mdx
To open the preview:
1. Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-122223-hcms-widgets) to set up the portal with this branch changes.
2. Access the following URL: https://developers.vtex.com/docs/guides/faststore/headless-cms-widgets
=> EDU-12223 - Update Headless CMS widgets doc

docs/localization/vtex-io-documentation-5-definingstyles.md
Tracked in task [LOC-15665 - DevPortal - Defining styles documentation update](https://vtex-dev.atlassian.net/browse/LOC-15665)
=> LOC-15665 - Defining styles documentation update

docs/guides/Integration-Guides/payments-integration-guide/split-payouts-on-payment-provider-protocol.md
PR created to add a new callout: partial refund stage information (EDU-13179).
=> New callout partial refund stage

docs/localization/i-am-getting-500-errors-in-vtex-io-cli.md
Tracked in [LOC-15521](https://vtex-dev.atlassian.net/browse/LOC-15521).
[LOC-15521]: https://vtex-dev.atlassian.net/browse/LOC-15521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> reviewed by Localization: EDU-12324 - VTEX IO CLI 500 error troubleshooting guide

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-making-a-custom-component-available-in-site-editor.mdx
…le-in-site-editor.mdx
- Added a callout informing about the [Site Editor schema examples](https://developers.vtex.com/docs/guides/vtex-io-documentation-site-editor-schema-examples) guide.
- Updated the `seeAlso` section to include the mentioned doc URL.
=> Adding callout and updating seeAlso

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-store-theme.md
[EDU-13195](https://vtex-dev.atlassian.net/browse/EDU-13195)
[EDU-13195]: https://vtex-dev.atlassian.net/browse/EDU-13195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc: Updating vtex-io-documentation-store-theme.md

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-manifest.md
[EDU-12875](https://vtex-dev.atlassian.net/browse/EDU-12875)
[EDU-12875]: https://vtex-dev.atlassian.net/browse/EDU-12875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12875 - Updating Manifest doc

docs/faststore/docs/api-extensions/best-practices.mdx, docs/faststore/docs/api-extensions/extending-queries-using-fragments.mdx, docs/faststore/docs/customization/api-extensions/extending-queries-using-fragments.mdx
Fixing the code example. The current one is broken.
=> Fix: Example fragment code

docs/guides/vtex-io/Storefront-Guides/vtex-io-documentation-going-live/vtex-io-documentation-migrating-storefront-from-legacy-to-io.md
…to-io.md
[EDU-10984
](https://vtex-dev.atlassian.net/browse/EDU-10984)
=> EDU-10984 - Updating Legacy to Store Framework migration doc

docs/localization/test.md
=> Create localization folder again

docs/guides/VTEX-Platform-Overview/Extensibility/extensibility.md
=> 24H1KR3: apply localization review to extensibility.md

docs/release-notes/2024-08-19-faststore-core-new-version.md
=> Fix(2024-06-28-faststore-core-new-version.md): Update frontmatter and filename

docs/localization/i-cant-integrate-my-external-search-provider.md
=> EDU-12068-I-cant-integrate-my-external-Search-Provider

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-integrating-frontend-app-with-site-editor.md
…e-editor.md
[EDU-12617](https://vtex-dev.atlassian.net/browse/EDU-12617)
[EDU-12617]: https://vtex-dev.atlassian.net/browse/EDU-12617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat/EDU-12617 - Integrating a frontend app with Site Editor

docs/faststore/components/index.mdx, docs/faststore/components/molecules/overview.mdx
Reference: [EDU-13278](https://vtex-dev.atlassian.net/browse/EDU-13278)
[EDU-13278]: https://vtex-dev.atlassian.net/browse/EDU-13278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13278: Fix 'Icon Button' link

docs/localization/i-cant-install-vtex-io-cli.md
Tracked in [LOC-15748](https://vtex-dev.atlassian.net/browse/LOC-15748).
[LOC-15748]: https://vtex-dev.atlassian.net/browse/LOC-15748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> reviewed by Localization: EDU-13089 - I can't install vtex io cli

docs/faststore/docs/getting-started/3-faststore-cli.mdx
This PR fixes broken links and also changes the instructions for the CLI installation due to a bug reported by the FS team.
=> EDU-13283 - FastStore CLI doc

docs/faststore/docs/faststore-api/schema/objects.mdx
=> Fix FastStore API schema markdown issues

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-ppp-applied-to-pos.md
PR created to add endpoint timeout information (EDU-13313).
=> Add endpoint timeout information

docs/faststore/docs/faststore-api/schema/queries.mdx, docs/troubleshooting/development/i-cant-install-vtex-io-cli.md
=> Fix: build errors due to docs typos

docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md, docs/guides/Integration-Guides/sent-offers-integration-guide-connectors/offer-management-sdk.md, docs/guides/Marketplace/marketplace-api-overview.md
Inclusion of callout on deprecation.
=> Deprecation Offer Management

docs/localization/managing-content-with-scopes-and-requiredscopes.md
It relates to the task [LOC-15728](https://vtex-dev.atlassian.net/browse/LOC-15728).
[LOC-15728]: https://vtex-dev.atlassian.net/browse/LOC-15728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc reviewed by Localization

docs/faststore/docs/api-extensions/api-extensions-use-cases/overview.mdx
LOC Review for the task [EDU-12991](https://vtex-dev.atlassian.net/browse/EDU-12991)
[EDU-12991]: https://vtex-dev.atlassian.net/browse/EDU-12991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12991 - LOC Review

docs/troubleshooting/development/my-store-catalog-does-not-show-the-price-range-filter.md
=> Update troubleshooting doc slug

docs/faststore/docs/headless-cms/managing-content-with-scopes-and-requiredscopes.mdx
Reference: [EDU-11632](https://vtex-dev.atlassian.net/browse/EDU-11632)
[EDU-11632]: https://vtex-dev.atlassian.net/browse/EDU-11632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-11632: LOC review

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md
=> Fix images

docs/guides/vtex-io/Getting-Started/back-end-development-guides/how-to-receive-catalog-changes-on-vtex-io.md
=> Update catalog events article

docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-a-contact-form-to-a-landing-page.mdx
Reference: [EDU-12992](https://vtex-dev.atlassian.net/browse/EDU-12992)
[EDU-12992]: https://vtex-dev.atlassian.net/browse/EDU-12992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12992: LOC review

docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-a-contact-form-to-a-landing-page.mdx
Add an open tag for the `<CH.Scrollycoding>`, fixing the following error:
More details: [Deploy log](https://app.netlify.com/sites/elated-hoover-5c29bf/deploys/66d7090219c6290008087165#L2334-L2346)
=> Fix: `<CH.Scrollycoding>` tag

docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-best-practices-for-associating-a-custom-page-with-a-content-type.md, docs/localization/vtex-io-documentation-associating-a-custom-page-to-a-content-type.md
…-type.md
[EDU-10961](https://vtex-dev.atlassian.net/browse/EDU-10961)
[EDU-10961]: https://vtex-dev.atlassian.net/browse/EDU-10961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-10961 - Feedback #3368 - Improvement

docs/faststore/docs/headless-cms/widgets.mdx
Reference: [EDU-12223](https://vtex-dev.atlassian.net/browse/EDU-12223)
[EDU-12223]: https://vtex-dev.atlassian.net/browse/EDU-12223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12223: Adding LOC review

docs/troubleshooting/store-performance/my-store-is-slow-or-unavailable.md
[EDU-12066](https://vtex-dev.atlassian.net/browse/EDU-12066)
[EDU-12066]: https://vtex-dev.atlassian.net/browse/EDU-12066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> edit my-store-is-slow-or-unavailable.md

docs/troubleshooting/api/i-cant-update-the-ean-of-my-skus-via-api.md
PR to add a new category to the troubleshooting page and move [I can't update the EAN of my SKUs via API](https://help.vtex.com/tutorial/i-cant-update-the-ean-of-my-skus-via-api--1gHfGo3TpSTHqb5ZNzwq3m) to the Developer Portal.
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/753
=> chore(troubleshooting): add new section for API issues

docs/localization/site-editor.md
Tracked in task [LOC-15926](https://vtex-dev.atlassian.net/browse/LOC-15926).
[LOC-15926]: https://vtex-dev.atlassian.net/browse/LOC-15926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-15926 - Working with Site Editor documentation

docs/localization/vtex-io-documentation-pixel-builder.md
Tracked in task [LOC-15947](https://vtex-dev.atlassian.net/browse/LOC-15947).
[LOC-15947]: https://vtex-dev.atlassian.net/browse/LOC-15947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-15947 - Pixel builder documentation

docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-using-sandbox-blocks.md, docs/guides/vtex-io/Storefront-Guides/managing-seo/vtex-io-documentation-understanding-how-store-url-indexing-works.md, docs/guides/vtex-io/Storefront-Guides/styling-your-store/vtex-io-documentation-customizing-your-stores-icons.md, docs/guides/vtex-io/Storefront-Guides/vtex-io-multi-language-stores/vtex-io-documentation-overwriting-the-messages-app.md
=> chore: remove introduction heading

docs/faststore/components/index.mdx, docs/faststore/components/organisms/overview.mdx
Reference: [EDU-13369](https://vtex-dev.atlassian.net/browse/EDU-13369)
[EDU-13369]: https://vtex-dev.atlassian.net/browse/EDU-13369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13369: Add the Newsletter to the Organisms overview

docs/release-notes/2024-09-09-updates-webops-permissions.md
`navigation.json` updates: https://github.com/vtexdocs/devportal/pull/760
=> EDU-13391 WebOps: Preview your store changes before deployment

docs/faststore/components/index.mdx, docs/faststore/components/molecules/overview.mdx, docs/faststore/components/molecules/product-price.mdx
1. Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-12637-product-price-component) to set up the portal with this branch changes.
2. Access the following
=> EDU-12637: Product Price (FS UI)

docs/release-notes/2024-09-09-updates-webops-permissions.md
This PR makes improvements to the images and gif sizes.
| **Before** | **After** |
| ----------- | ---------- |
| ![before-webops](https://github.com/user-attachments/assets/cf5e4fe1-8761-4a0a-82e5-7089ecf8ee26) |![after-webops](https://github.com/user-attachments/assets/405f568e-a9c3-4dcb-b8fa-0d9fc52097cf) |
=> EDU-13391: Review release note media size

docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-installment-information-in-the-product-details-page.mdx
Thir PR adds the Localization review for the [Adding Installment Information in the Product Details Page](https://developers.vtex.com/docs/guides/faststore/api-extensions-use-cases-adding-installment-information-in-the-product-details-page) doc.
=> EDU-12994: LOC review

docs/guides/Subscriptions/how-to-keep-attachments-from-original-orders-in-subscriptions.md
This article has been reviewed by the Localization team.
=> New article how to keep attachments from original orders in subscriptions

docs/faststore/components/index.mdx, docs/faststore/components/molecules/card.mdx, docs/faststore/components/molecules/overview.mdx
To open the doc preview:
1. Open [this URL](https://developers.vtex.com/api/preview?branch=EDU-13292-card-component) to set up the portal with this branch changes.
2. Access the following link: https://developers.vtex.com/docs/guides/faststore/molecules-card
- updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/768
=> EDU-13292: New card component

docs/localization/vtex-io-documentation-messages-builder.md
Tracked in task [LOC-15903](https://vtex-dev.atlassian.net/browse/LOC-15903).
[LOC-15903]: https://vtex-dev.atlassian.net/browse/LOC-15903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-15903 - DP - Messages builder on VTEX IO documentation

docs/guides/Integration-Guides/headless-commerce/headless-cart-and-checkout.md
=> EDU-12833 General update on Headless Checkout guide

docs/guides/vtex-io/Storefront-Guides/store-framework-styling.md
=> Update and rename styling.md to store-framework-styling.md

docs/faststore/docs/routing/managing-urls-with-redirects-and-rewrite-paths.mdx
Obs.: Tarefa para Loc já foi criada ([LOC-16569](https://vtex-dev.atlassian.net/browse/LOC-16569))
[LOC-16569]: https://vtex-dev.atlassian.net/browse/LOC-16569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12795: Managing URLs with redirects and rewrite paths

docs/guides/Pricing/contextual-price-per-seller.md
=> EDU-13282 New Contextual Seller Pricing documentation

docs/localization/vtex-io-documentation-updating-live-stores.md
Tracked in [LOC-16307](https://vtex-dev.atlassian.net/browse/LOC-16307).
[LOC-16307]: https://vtex-dev.atlassian.net/browse/LOC-16307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-12177 - Doc reviewed by Localization

docs/faststore/components/atoms/button.mdx
=> EDU-13415 FastStore UI components: fix button.mdx

docs/guides/Integration-Guides/payments-integration-guide/how-the-integration-protocol-between-vtex-and-antifraud-companies-works.md
PR was created to add a new callout (EDU-13452)
=> New callout antifraud transactions information

docs/faststore/docs/customization/building-sections/list-of-native-sections.mdx
Remove `Price` from the override list and fix component names
=> EDU-12408: Update `ProductDetails` override components 

docs/guides/Integration-Guides/data-privacy/limitations-of-the-pii-data-architecture-during-closed-beta.md
[EDU-13477](https://vtex-dev.atlassian.net/browse/EDU-13477)
[EDU-13477]: https://vtex-dev.atlassian.net/browse/EDU-13477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update master data section - pii limitations guide

docs/release-notes/2024-09-26-apps-and-payment-connector-homologation-freeze-in-preparation-for-black-friday-2024.md
PR was created to publish the Release Note: "Apps and payment connector homologation freeze in preparation for Black Friday 2024" (EDU-13522).
Note: The content is from the [2023 Release Note](https://developers.vtex.com/updates/release-notes/apps-and-payment-connector-homologation-freeze-in-preparation-for-black-friday-2023), only the dates have been modified.
=> Apps and payment connector homologation freeze in preparation for bf 2024

docs/guides/Integration-Guides/erp-integration-guide/erp-integration-set-up-order-integration.md
=> Fix: Change get feed configuration endpoint

docs/guides/VTEX-Platform-Overview/vtex-platform-overview.md
=> add extensibility card to vtex-platform-overview.md

docs/faststore/components/organisms/banner-text.mdx, docs/faststore/components/organisms/cart-sidebar.mdx, docs/faststore/components/organisms/empty-state.mdx, docs/faststore/components/organisms/filter-slider.mdx, docs/faststore/components/organisms/filter.mdx, docs/faststore/components/organisms/hero.mdx, docs/faststore/components/organisms/image-gallery.mdx, docs/faststore/components/organisms/navbar-slider.mdx, docs/faststore/components/organisms/navbar.mdx, docs/faststore/components/organisms/newsletter.mdx, docs/faststore/components/organisms/out-of-stock.mdx, docs/faststore/components/organisms/overview.mdx, docs/faststore/components/organisms/payment-methods.mdx, docs/faststore/components/organisms/price-range.mdx, docs/faststore/components/organisms/product-grid.mdx, docs/faststore/components/organisms/product-shelf.mdx, docs/faststore/components/organisms/region-modal.mdx, docs/faststore/components/organisms/search-input.mdx, docs/faststore/components/organisms/shipping-simulation.mdx, docs/faststore/components/organisms/slide-over.mdx
=> EDU-13415: Review FastStore components' name (Organisms)

docs/faststore/docs/customization/building-sections/override-use-cases/adding-more-icon-options-to-the-alert-component.mdx
Added a gif to show the Headless CMS interface with the available icons
=> EDU-12885: Feedback #3937 - Improvement

docs/guides/vtex-io/Calling Commerce APIs/calling-commerce-apis-1-getting-the-service-app-boilerplate.mdx, docs/guides/vtex-io/Calling Commerce APIs/calling-commerce-apis-3-using-vtex-io-clients.md, docs/guides/vtex-io/Getting-Started/back-end-development-guides/node-builder-7x-migration-guide.md, docs/guides/vtex-io/Getting-Started/back-end-development-guides/vtex-io-documentation-developing-service-configuration-apps.md, docs/guides/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-engineering-guidelines.md, docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-node-builder.md, docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-collecting-user-session-data.md, docs/guides/vtex-io/services/services-1-getting-started-with-the-boilerplate.mdx, docs/guides/vtex-io/services/services-6-graphql-retrieving-data-from-master-data.mdx, docs/release-notes/2024-10-10-node-builder-update-to-version-7x-and-deprecation-of-previous-builder-versions.md
=> EDU-13390 - Node builder 7.x

docs/guides/B2B-Suite/settings/how-to-configure-tradename-to-use-in-the-organization-search-field.md
=> Changed slug

docs/localization/2024-10-18-build-logs-integrated-into-webops.md
Localization review of the Release note: Build logs now integrated into the WebOps app. It relates to [LOC-16685](https://vtex-dev.atlassian.net/browse/LOC-16685)
[LOC-16685]: https://vtex-dev.atlassian.net/browse/LOC-16685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC Review: Release note: Build logs now integrated into the WebOps app

docs/localization/2024-10-18-build-logs-integrated-into-webops.md, docs/release-notes/2024-10-17-build-logs-integrated-into-webops.md
Atualização da navbar: https://github.com/vtexdocs/devportal/pull/800
=> EDU-12937 - Release note: Build logs now integrated into the WebOps app

docs/faststore/docs/api-extensions/extending-api-schema.mdx
PR to fix the [Feedback #4200](https://vtex-dev.atlassian.net/browse/EDU-13678).
=> EDU-13678: Fix `resolver` extension name (Feedback #4200)

.github/scripts/check-links-pr.mjs, .github/workflows/check-links-pr.yml
=> feat: new action that checks broken links

.github/workflows/check-styleguide.yml
=> fix: script path

docs/faststore/docs/customization/using-themes/overview.mdx
This PR fixes some doc typos and review section's titles.
=> EDU-12703: Review 'Theming' doc

docs/faststore/docs/customization/building-sections/overview.mdx
=> Fix: closing tag for <Steps>

docs/faststore/docs/customization/building-sections/list-of-native-sections.mdx
=> Fix: code block syntax

docs/release-notes/2024-11-01-webops-installation.md
Updating navigation.json: https://github.com/vtexdocs/devportal/pull/812
=> EDU-13709: Release note - Users can now install the FastStore WebOps app by themselves - 

docs/guides/vtex-io/Getting-Started/back-end-development-guides/node-builder-7x-migration-guide.md, docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-node-builder.md, docs/release-notes/2024-10-10-node-builder-update-to-version-7x-and-deprecation-of-previous-builder-versions.md
=> Update node builder 7.x content with LOC review

docs/release-notes/2024-11-04-new-password-field-for-sending-secure-data-in-the-anti-fraud-flow.md
PR created to publish the Release Note: New password field for sending secure data in the anti-fraud flow (EDU-13452).
=> Release Note New password field for sending secure data the anti-fraud

docs/localization/overview.mdx, docs/localization/test.md
Tracked in task [LOC-17129](https://vtex-dev.atlassian.net/browse/LOC-17129).
[LOC-17129]: https://vtex-dev.atlassian.net/browse/LOC-17129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17129 - FastStore SDK documentation

docs/localization/managing-product-images-in-specific-contexts.md, docs/localization/test.md
Tracked in task [LOC-17130](https://vtex-dev.atlassian.net/browse/LOC-17130).
[LOC-17130]: https://vtex-dev.atlassian.net/browse/LOC-17130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17130 - Managing product images in specific contexts documentation

docs/guides/vtex-io/Storefront-Guides/store-framework-building-pages.md
=> Fixing slug

docs/guides/vtex-io/Storefront-Guides/store-framework-dealing-with-events.md
=> Dealing with events - Fixing slug

docs/guides/vtex-io/Storefront-Guides/store-framework-working-with-site-editor.md
=> Working with Site Editor - fixing slug

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-framework.md
PR created to include custom field information in the Payment Provider Framework guide (EDU-13791).
=> Update custom field information Payment Provider Framework

docs/guides/Orders/order-canceling-improvements.md
=> Fix typo order canceling improvements

docs/localization/vtex-io-documentation-managing-application-logs.md
Tracked in [LOC-17267](https://vtex-dev.atlassian.net/browse/LOC-17267).
[LOC-17267]: https://vtex-dev.atlassian.net/browse/LOC-17267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc reviewed by Localization.

docs/guides/vtex-io/Getting-Started/back-end-development-guides/node-builder-7x-migration-guide.md
=> Add video reference to node builder migration guide

docs/faststore/docs/customization/managing-product-images-in-specific-contexts.md, docs/faststore/docs/customization/managing-product-images-in-specific-contexts.mdx, docs/localization/managing-product-images-in-specific-contexts.md
=> EDU-11660: Managing product images in specific contexts

docs/faststore/docs/faststore-api/schema/mutations.mdx
=> EDU-13753: validateCart mutation KI reference

docs/release-notes/2024-11-21-store-framework-sitemap-generation-disabled-during-shopping-season.md
[EDU-13837](https://vtex-dev.atlassian.net/browse/EDU-13837)
[EDU-13837]: https://vtex-dev.atlassian.net/browse/EDU-13837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release note: Sitemap generation disabled during Shopping Season

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-ppp-applied-to-pos.md
PR was created to update VTEX Sales APP POS information (EDU-13857).
=> Update information VTEX Sales APP POS

docs/localization/improving-store-performance-with-preact.md
Tracked in task [LOC-17416](https://vtex-dev.atlassian.net/browse/LOC-17416).
[LOC-17416]: https://vtex-dev.atlassian.net/browse/LOC-17416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17416 - Improving store performance with Preact documentation

docs/localization/vtex-io-documentation-optimizing-image-rendering.md
It relates to the task [LOC-17536](https://vtex-dev.atlassian.net/browse/LOC-17536).
[LOC-17536]: https://vtex-dev.atlassian.net/browse/LOC-17536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc reviewed by Localiization

docs/localization/test.md, docs/localization/use-analytics-event.md
Tracked in task [LOC-17546](https://vtex-dev.atlassian.net/browse/LOC-17546).
[LOC-17546]: https://vtex-dev.atlassian.net/browse/LOC-17546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17546 - FastStore Analytics - useAnalyticsEvent function documentation

docs/localization/catalog-internationalization.md
Tracked in task [LOC-17435](https://vtex-dev.atlassian.net/browse/LOC-17435).
[LOC-17435]: https://vtex-dev.atlassian.net/browse/LOC-17435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17435 - How to overwrite an automatic message translation from the Catalog documentation

docs/localization/do-not-remove.md
=> Do not remove file

docs/guides/Integration-Guides/data-privacy/working-with-schemas-in-the-profile-system.md
=> remove custom alternate keys information

docs/release-notes/2024-12-13-discovery-config-file.md, docs/release-notes/2024-12-16-discovery-config-file.md
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/840
=> EDU-13931 - Release note: Rename 'faststore.config' file to 'discovery.config'

docs/faststore/docs/api-extensions/api-extensions-use-cases/adding-installment-information-in-the-product-details-page.mdx, docs/faststore/docs/getting-started/2-setting-up-the-project.mdx, docs/faststore/docs/go-live/2-configuring-external-dns.mdx, docs/faststore/docs/headless-cms/1-configuring-the-vtex-account.mdx, docs/faststore/docs/headless-cms/multiple-page-template.mdx, docs/faststore/docs/reference/project-structure/config-options.mdx, docs/faststore/docs/reference/project-structure/custom-cypress.mdx, docs/faststore/docs/reference/themes/midnight.mdx, docs/faststore/docs/reference/themes/overview.mdx, docs/faststore/docs/reference/themes/soft-blue.mdx
Tasks related:
- Release note: https://developers.vtex.com/updates/release-notes/2024-12-16-discovery-config-file
- Feedback #4291: https://vtex-dev.atlassian.net/browse/EDU-14008
=> EDU-13805: Update 'faststore.config.js' mentioning to 'discovery.config.js'

docs/faststore/components/molecules/product-card.mdx
=> EDU-13917: Update `product-card.mdx`

docs/localization/vtex-io-documentation-enabling-performance-settings.md
[EDU-13729](https://vtex-dev.atlassian.net/browse/EDU-13729)
[EDU-13729]: https://vtex-dev.atlassian.net/browse/EDU-13729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13729 - Enabling performance settings

docs/faststore/docs/managing-performance/improving-store-performance-with-preact.mdx
=> EDU-13989: Review Preact doc

docs/guides/Fulfillment/multilevel-omnichannel-inventory/change-orders-multilevel-omnichannel-inventory-external-marketplaces.md, docs/guides/Fulfillment/multilevel-omnichannel-inventory/multilevel-omnichannel-inventory-api-integration.md
Addition of a callout about the type of integration supported by MOI and creation of a task for the OMS team to review the integration.
=> EDU-14016 | Deprecation of MOI for Integrations with External Marketplaces

docs/release-notes/2024-12-20-new-sponsored-count-parameter.md
=> FastStore release note: Fix code example

docs/release-notes/2024-12-23-faststore-improvements.md
=> EDU-13987: [Release note] FastStore: Performance improvements for mobile devices

docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
=> EDU-14042: Add `useScreenResize` to list of experimental hook

docs/release-notes/2025-01-08-simplified-lighthouse-dependency.md
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/854
=> EDU-13690: FastStore - Simplified Lighthouse dependency for projects

docs/faststore/docs/integrating-with-vtex-products/integrating-with-vtex-ad-network.mdx
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/850
=> EDU-13472: Integrating FastStore with VTEX Ad network

docs/release-notes/2025-01-06-integrating-faststore-with-vtex-ad-network.md
=> EDU-13833: Release note - Integration between FastStore and VTEX Ad Networkd

docs/guides/Master-Data/guides/sending-emails-with-triggers-in-master-data-v2.md
[EDU-14107](https://vtex-dev.atlassian.net/browse/EDU-14107)
[EDU-14107]: https://vtex-dev.atlassian.net/browse/EDU-14107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> edit sending-emails-with-triggers-in-master-data-v2.md

docs/localization/vtex-io-documentation-creating-a-quickview-using-modal-layout.md, docs/localization/vtex-io-documentation-migrating-cms-settings-after-major-update.md
Tracked in task [LOC-17886 - How to create a Quickview feature using the Modal Layout app documentation](https://vtex-dev.atlassian.net/browse/LOC-17886)
=> LOC-17886 - How to create a Quickview feature using the Modal Layout app documentation

docs/faststore/docs/routing/managing-urls-with-redirects-and-rewrite-paths.mdx, docs/guides/vtex-io/Storefront-Guides/storefront-seo.md
This PR changes the filename from `faststore.config` to `discovery.config`
=> Fix: `discovery.config.js` filename

docs/localization/vtex-io-documentation-migrating-cms-settings-after-major-update.md
Tracked in [LOC-17990](https://vtex-dev.atlassian.net/browse/LOC-17990).
[LOC-17990]: https://vtex-dev.atlassian.net/browse/LOC-17990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17990 - Setting up brand search queries as full text documentation

docs/localization/store-framework-using-advanced-layouts.md
TRacked in task [LOC-18112 - How to create advanced layouts in your store documentation](https://vtex-dev.atlassian.net/browse/LOC-18112)
=> LOC-18112 -How to create advanced layouts in your store documentation

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx
Updating the WebOps dashboard after UI improvements (EDU-14075 - Feedback #4311)
=> EDU-14075: Update WebOps dashboard guide

docs/guides/vtex-io/Storefront-Guides/store-framework-using-advanced-layouts.md, docs/localization/store-framework-using-advanced-layouts.md
[EDU-13404](https://vtex-dev.atlassian.net/browse/EDU-13404)
[EDU-13404]: https://vtex-dev.atlassian.net/browse/EDU-13404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13404 - Category cover: Using advanced layouts

docs/localization/vtex-io-documentation-customizing-your-404-page.md
Tracked in task [LOC-18110 - DP - Customizing your 404 page documentation](https://vtex-dev.atlassian.net/browse/LOC-18110)
=> LOC-18110 - Customizing your 404 page documentation

docs/localization/README.md
Tracked in [LOC-17948](https://vtex-dev.atlassian.net/browse/LOC-17948).
[LOC-17948]: https://vtex-dev.atlassian.net/browse/LOC-17948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17948 - README: Contributing with Developer Portal documentation

docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-customizing-your-404-page.md, docs/localization/vtex-io-documentation-customizing-your-404-page.md
[EDU-13880](https://vtex-dev.atlassian.net/browse/EDU-13880)
[EDU-13880]: https://vtex-dev.atlassian.net/browse/EDU-13880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13880 - Create 'Customizing your 404 page'

docs/localization/vtex-io-documentation-making-your-theme-content-public.md
Tracked in [LOC-17884](https://vtex-dev.atlassian.net/browse/LOC-17884).
[LOC-17884]: https://vtex-dev.atlassian.net/browse/LOC-17884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-17884 - How to make your store theme public documentation

docs/localization/do-not-remove.md, docs/localization/vtex-io-documentation-3-settingyourstoretheme.md
Tracked in [LOC-18150](https://vtex-dev.atlassian.net/browse/LOC-18150).
[LOC-18150]: https://vtex-dev.atlassian.net/browse/LOC-18150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-18150 - Creating your first store theme project documentation

docs/guides/vtex-io/Storefront-Guides/store-framework-using-components.md
Updating docs in 'Guides in this section'
=> Updating docs within 'Guides in this section'

docs/localization/search-overview.md
Tracked in task [LOC-18335 - FastStore SDK - Search overview documentation](https://vtex-dev.atlassian.net/browse/LOC-18335).
=> LOC-18335 - FastStore SDK - Search overview documentation

docs/faststore/docs/sdk/analytics/overview.mdx
=> EDU-14226: Update Analytics overview

docs/faststore/docs/go-live/2-integrating-the-vtex-login.mdx
This PR reviews and fixes [Step 1](https://developers.vtex.com/docs/guides/faststore/go-live-2-integrating-the-vtex-login#step-1-adding-a-redirect-back-to-your-faststore-domain) by creating two new sections so the user can create the redirect based on the store technology where the My Account and Checkout pages are hosted and add the instructions on how to do that for each technology.
=> EDU-12969: Review 'Integrating the VTEX Login'

docs/faststore/docs/go-live/1-configuring-external-dns.mdx
=> EDU-14315: Update 1-configuring-external-dns.mdx

docs/guides/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-enabling-performance-settings.md
Fixed the markdown for adding a link.
=> fixing markdown

docs/localization/do-not-remove.md, docs/localization/vtex-io-documentation-5-definingstyles.md
Tracked in [LOC-18155](https://vtex-dev.atlassian.net/browse/LOC-18155).
[LOC-18155]: https://vtex-dev.atlassian.net/browse/LOC-18155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-18155 - How to set specific styles for your store components documentation

docs/guides/vtex-io/Storefront-Guides/storefront-best-practices/storefront-best-practices.md
Adding `Accessibility` doc to the category cover.
=> adding `Accessibility` to category cover

docs/guides/Master-Data/understanding-master-data/master-data-infrastructure.md
[EDU-13918](https://vtex-dev.atlassian.net/browse/EDU-13918)
[EDU-13918]: https://vtex-dev.atlassian.net/browse/EDU-13918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> review master data infrastructure guide

docs/localization/vtex-io-documentation-vtex-io-cli-install.md
Tracked in task [LOC-18432 - VTEX IO CLI install guide documentation improvement](https://vtex-dev.atlassian.net/browse/LOC-18432).
=> LOC-18432 - VTEX IO CLI install guide documentation improvement

docs/guides/Master-Data/understanding-master-data/data-consistency-and-synchronization-in-master-data.md
=> review data consistency guide

docs/guides/Integration-Guides/pricing-hub.md, docs/guides/Integration-Guides/pricing-hub/seller-price.md
=> EDU-14389 Document deprecation

docs/guides/Integration-Guides/data-privacy/profile-system.md
[EDU-13742](https://vtex-dev.atlassian.net/browse/EDU-13742)
[EDU-13742]: https://vtex-dev.atlassian.net/browse/EDU-13742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update profile-system.md audit events

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
PR created to add QR Code PIX expiration time information (EDU-13761).
=> Update PIX expiration time

docs/faststore/docs/api-extensions/best-practices.mdx, docs/faststore/docs/headless-cms/managing-content-with-scopes-and-requiredscopes.mdx, docs/faststore/docs/integrating-with-vtex-products/integrating-with-vtex-ad-network.mdx, docs/faststore/docs/managing-performance/improving-store-performance-with-preact.mdx, docs/faststore/docs/reference/project-structure/updating-the-cli-package-version.mdx
=> fix: faststore typo

docs/faststore/docs/headless-cms/multiple-page-template.mdx
P.S.: This is a stopgap solution. One idea would be to bring up the issue of how our portal is rendering the mermaid diagrams to the "Development Sprints KR" and check if we can create a task, and I volunteer to take it on.
=> EDU-13146: Fixed mermaid diagram

docs/faststore/docs/headless-cms/2-setting-up-the-headless-cms.mdx, docs/faststore/docs/headless-cms/overview.mdx
In addition to basic CMS resources, the user role requires the `Vbase read write` resource to run `fatstore cms-sync`. This PR also fixes some typos.
=> EDU-14338: Update Headless CMS overview

docs/faststore/docs/api-extensions/extending-api-schema.mdx, docs/faststore/docs/api-extensions/overview.mdx, docs/release-notes/2023-10-11-faststore-v1-abandoned-cart.md, docs/troubleshooting/store-performance/my-store-is-slow-or-unavailable.md
=> Fix: FastStore links

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-node-builder.md
Add version 3.x to the Node builder versioning list
=> Add Node builder 3.x

docs/faststore/docs/sdk/overview.mdx
=> EDU-13379: FastStore SDK overview

docs/guides/faststore/faststore.md
=> EDU-14588: Fix outdated information (FastStore quickstart)

docs/faststore/docs/getting-started/overview.mdx
We no longer use the Onboarding app.
=> fix(overview.mdx): Fix card mentioning Onboarding app

docs/release-notes/2025-03-10-payments-gateway-api-new-permission-required-for-approving-payments.md
=> Fix creation date

docs/localization/use-search.md
Tracked in [LOC-19130](https://vtex-dev.atlassian.net/browse/LOC-19130).
[LOC-19130]: https://vtex-dev.atlassian.net/browse/LOC-19130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19130 - EDU-14099 - FastStore Search module: useSearch documentation

docs/faststore/docs/customization/dynamic-content/step-1-setting-up-the-store-code-for-dynamic-content.mdx
=> EDU-14405: Fix code blocks

docs/localization/2025-03-14-vtex-id-api-new-endpoints-for-token-renewal.md
Tracked in [LOC-19236](https://vtex-dev.atlassian.net/browse/LOC-19236).
[LOC-19236]: https://vtex-dev.atlassian.net/browse/LOC-19236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19236 - EDU-14478 - API Key token renewal - release notes

docs/guides/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-setting-your-apps-billing-model.md
=> EDU-8672 Atualização e correção da fórmula

docs/localization/standard-content-types-in-faststore-projects.md
Tracked in [LOC-19133](https://vtex-dev.atlassian.net/browse/LOC-19133).
[LOC-19133]: https://vtex-dev.atlassian.net/browse/LOC-19133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  LOC-19133 - EDU-14376: Standard Content Types in FastStore projects

docs/localization/use-pagination.md
Tracked in task [LOC-19131 - DevPortal - FastStore Search module usePagination documentation](https://vtex-dev.atlassian.net/browse/LOC-19131).
=> LOC-19131 - DevPortal - FastStore Search module usePagination documentation

docs/faststore/docs/sdk/search/overview.mdx, docs/faststore/docs/sdk/search/search-provider.mdx, docs/faststore/docs/sdk/search/use-pagination.mdx, docs/faststore/docs/sdk/search/use-search.mdx, docs/localization/search-overview.md
Obs.: A doc estará visível no portal uma vez que publicarmos as outras três docs do módulo de Search.
`navigation.json`: https://github.com/vtexdocs/devportal/pull/910
=> EDU-13382: FastStore Search 

docs/release-notes/2025-03-14-vtex-id-api-new-endpoints-for-token-renewal.md
=> move vtex id release notes and add updatedAt to frontmatter

docs/faststore/docs/headless-cms/overview.mdx
=> EDU-14376: LOC review

docs/guides/Integration-Guides/headless-commerce/headless-authentication.md
[EDU-14463](https://vtex-dev.atlassian.net/browse/EDU-14463)
[EDU-14463]: https://vtex-dev.atlassian.net/browse/EDU-14463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix headless authentication provider example

docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
=> fix(native-component.mdx): step 4 code, indentation and typos

docs/release-notes/2025-03-24-discontinuation-of-the-pricing-v1-module-compatiblity-routes.md
=> EDU-14557 New release notes Discontinuation of the Pricing V1 module compatibility routes

docs/guides/Integration-Guides/payments-integration-guide/layout-development-guide-for-payment-methods-in-smart-checkout-vtex.md
PR created to update a callout, adding custom payment method examples. (EDU-14760).
=> Update callout Layout Development Guide

docs/faststore/docs/sdk/session.mdx
Agreements with Localization: After the LOC review, I'll update this guide with their suggestions.
=> EDU-14516: Add FastStore Session module

docs/release-notes/2025-03-20-operational-capacity-api.md
=> EDU-14390-Operational-Capacity-API-release-note

docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-node-builder.md, docs/release-notes/2024-10-10-node-builder-update-to-version-7x-and-deprecation-of-previous-builder-versions.md
Tracked in [LOC-19664](https://vtex-dev.atlassian.net/browse/LOC-19664).
[LOC-19664]: https://vtex-dev.atlassian.net/browse/LOC-19664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19664 -  EDU-14629: Update Node builder deprecation message

docs/faststore/docs/sdk/analytics/sending-custon-events.mdx
Reference: https://github.com/vtexdocs/devportal/pull/927
=> EDU-13545: FastStore Analytics: Sending custom events

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx
[EDU-14845](https://vtex-dev.atlassian.net/browse/EDU-14845)
[EDU-14845]: https://vtex-dev.atlassian.net/browse/EDU-14845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14845 - [Publicação] - Atualizar `FastStore WebOps - Dashboard`

docs/faststore/docs/go-live/1-configuring-external-dns.mdx
[EDU-14844](https://vtex-dev.atlassian.net/browse/EDU-14844)
[EDU-14844]: https://vtex-dev.atlassian.net/browse/EDU-14844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14844 - [Publicação] Atualizar documentação de go-live usando o FastStore WebOps

docs/release-notes/2025-04-04-faststore-webops-self-service-domain-setup-now-available.md, docs/release-notes/2025-04-08-faststore-webops-self-service-domain-setup-now-available.md
[EDU-14848](https://vtex-dev.atlassian.net/browse/EDU-14848)
[EDU-14848]: https://vtex-dev.atlassian.net/browse/EDU-14848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14848 - [Publicação] - Release note: Settings - WebOps Dashboard

docs/localization/vtex-io-documentation-creating-robots-files-for-cross-border-stores.md
Tracked in [LOC-19385](https://vtex-dev.atlassian.net/browse/LOC-19385).
[LOC-19385]: https://vtex-dev.atlassian.net/browse/LOC-19385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19385 - EDU-14051 - Feedback #4300 - Improvement

docs/faststore/components/molecules/modal.mdx
[EDU-14630](https://vtex-dev.atlassian.net/browse/EDU-14630)
[EDU-14630]: https://vtex-dev.atlassian.net/browse/EDU-14630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14630 - Updates Modal doc with ModalFooter

docs/localization/2025-03-11-store-image-component-improved-image-dimension-handling.md
Tracked in [LOC-19471](https://vtex-dev.atlassian.net/browse/LOC-19471).
[LOC-19471]: https://vtex-dev.atlassian.net/browse/LOC-19471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19471 - EDU-14653 - Release note: Feature/height siteeditor

docs/faststore/components/molecules/rating-field.mdx
[EDU-14918
](https://vtex-dev.atlassian.net/browse/EDU-14918)
=> EDU-14918 - RatingField

docs/localization/refresh-token-flow-for-headless-implementations.md
=> Apply loc review: refresh-token-flow-for-headless-implementations.md

docs/release-notes/2025-04-16-new-delivery-promise-notification-api.md
=> feat: add new release note

docs/localization/1-configuring-external-dns.mdx
=> Apply Localization review

docs/guides/Fulfillment/vtex-pick-and-pack/vtex-pick-and-pack-get-order-status-and-information-api.md
=> EDU-11664 fix: fix 404 links

docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
=> EDU-14964: Add new experimental hooks

docs/localization/vtex-io-documentation-using-the-fold-blocks.md
Tracked in [LOC-19473](https://vtex-dev.atlassian.net/browse/LOC-19473).
[LOC-19473]: https://vtex-dev.atlassian.net/browse/LOC-19473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19473 - EDU-14087 - Feedback #4316 - Error

docs/release-notes/2025-04-25-pick-and-pack-api.md
=> EDU-14427  feat: add release note

docs/release-notes/2025-04-25-pick-and-pack-api.md
=> fix: fix links

docs/faststore/docs/faststore-api/configuring-graphql-cache-control.mdx
=> EDU-14827: Configuring GraphQL cache control for GET requests

docs/localization/optimizing-seo-by-managing-lazy-loading-on-plp.md
Tracked in [LOC-19412](https://vtex-dev.atlassian.net/browse/LOC-19412).
[LOC-19412]: https://vtex-dev.atlassian.net/browse/LOC-19412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19412 - EDU-14302: LOC review doc

docs/faststore/docs/api-extensions/extending-queries-using-fragments.mdx, docs/release-notes/2025-04-30-faststore-custom-queries.md
This PR adds a release note related to the incident #inc-2443. 
Updating `navigation.json`: https://github.com/vtexdocs/devportal/pull/954
🎗️ **Next steps:** Create a task to mock a use case example for creating custom queries on the [playground.store](https://github.com/vtex-sites/playground.store) repo, and based on this, create a use case guide for the Dev Portal.
=> EDU-14842: Add store caching behavior information

docs/localization/cart-provider.md
Tracked in [LOC-19920](https://vtex-dev.atlassian.net/browse/LOC-19920).
[LOC-19920]: https://vtex-dev.atlassian.net/browse/LOC-19920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19920 - EDU-13749 CartProvider

docs/localization/2025-04-25-vtex-io-ttl-parameter-standardizeded-for-all-io-apps.md, docs/localization/vtex-io-documentation-service.md
Tracked in [LOC-19928](https://vtex-dev.atlassian.net/browse/LOC-19928).
[LOC-19928]: https://vtex-dev.atlassian.net/browse/LOC-19928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19928 - Add VTEX IO TTL update release note and callout 

docs/localization/2025-04-30-breadcrumb-improvement.md
Tracked in task [LOC-19947](https://vtex-dev.atlassian.net/browse/LOC-19947).
[LOC-19947]: https://vtex-dev.atlassian.net/browse/LOC-19947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19947 - Improved breadcrumb navigation in FastStore documentation

docs/guides/vtex-io/GraphQL/graphql-in-vtex-io.md
=> Add GraphQL in VTEX IO section cover

docs/guides/Integration-Guides/session-manager.md
[EDU-15044](https://vtex-dev.atlassian.net/browse/EDU-15044)
[EDU-15044]: https://vtex-dev.atlassian.net/browse/EDU-15044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix broken link on session-manager.md

docs/guides/B2B-Suite/b2b-organizations/bulk-import-buyer-organizations-spreadsheet.md
=> EDU-14973 Broken link and added callout

docs/localization/2025-04-02-faststore-webops-self-service-domain-setup-now-available.md
Tracked in [LOC-19868](https://vtex-dev.atlassian.net/browse/LOC-19868).
[LOC-19868]: https://vtex-dev.atlassian.net/browse/LOC-19868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19868 - EDU-14759 - Release note: Settings - WebOps Dashboard

docs/localization/sending-custom-events.md
Tracked in task [LOC-19910](https://vtex-dev.atlassian.net/browse/LOC-19910).
[LOC-19910]: https://vtex-dev.atlassian.net/browse/LOC-19910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19910 - Sending custom events in FastStore Analytics documentation

docs/localization/textarea.mdx
Tracked in [LOC-19899](https://vtex-dev.atlassian.net/browse/LOC-19899).
[LOC-19899]: https://vtex-dev.atlassian.net/browse/LOC-19899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19899 - EDU-14451: Textarea component

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx
=> fix: Update dashboard.mdx

docs/release-notes/2025-05-06-marketplace-api-new-affiliate-endpoints.md
=> EDU-14919 feat: add release note

docs/faststore/docs/getting-started/1-onboarding/dashboard.mdx
=> Fixing image links - FastStore WebOps - Dashboard

docs/faststore/docs/getting-started/1-onboarding/starting-the-project.mdx, docs/guides/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-developing-an-app.md
=> fix: capitalization

docs/localization/rating-field.mdx
Tracked in task [LOC-19992](https://vtex-dev.atlassian.net/browse/LOC-19992).
[LOC-19992]: https://vtex-dev.atlassian.net/browse/LOC-19992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-19992 - RatingField documentation

docs/faststore/components/features/my-account/extensions.mdx, docs/faststore/components/features/my-account/overview.mdx
=> Fixing My Account documentation

.github/scripts/get_feedback.py, .github/workflows/get_feedback_on_ai_reviewer.yml
=> Feat/add get feedback on ai reviewer.yml

docs/guides/Search/delivery-promise-for-headless-stores.md
=> add delivery promise for headless stores guide

docs/faststore/components/features/my-account/extensions.mdx, docs/faststore/components/features/my-account/overview.mdx
=> Hiding My Account documentation

docs/faststore/docs/api-extensions/overview.mdx
=> EDU-13853: Informing users about issues between FastStore API and other VTEX APIs

crowdin.yml, docs/localization/2025-04-30-faststore-custom-queries.md
Tracked in [LOC-20143](https://vtex-dev.atlassian.net/browse/LOC-20143).
[LOC-20143]: https://vtex-dev.atlassian.net/browse/LOC-20143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  LOC-20143 - EDU-14842: Add LOC review

docs/guides/Pricing/pricing-api-overview.md
=> EDU-15072 hidden document to be redirected

docs/faststore/docs/seo/validating-utm-tracking-in-faststore.mdx
P.S.: We will publish this guide and open an LOC review afterward. This is because the feature is already in production.
=> EDU-15157: Validating UTM tracking in FastStore

docs/localization/extensions.md
Tracked in task [LOC-20159](https://vtex-dev.atlassian.net/browse/LOC-20159)
[LOC-20159]: https://vtex-dev.atlassian.net/browse/LOC-20159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20159 - Extending My Account documentation

docs/release-notes/2025-05-23-legacy-webservice-api-deprecation.md
=> Release note - Legacy Webservice API deprecation

docs/faststore/components/atoms/overview.mdx, docs/faststore/components/molecules/overview.mdx
[EDU-14888](https://vtex-dev.atlassian.net/browse/EDU-14888)
[EDU-14888]: https://vtex-dev.atlassian.net/browse/EDU-14888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-14888 - Atualizar capas de categoria dentro de UI Components

docs/localization/review-card.md
Tracked in [LOC-20320](https://vtex-dev.atlassian.net/browse/LOC-20320).
[LOC-20320]: https://vtex-dev.atlassian.net/browse/LOC-20320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20320 - EDU-14916 - ReviewCard

docs/localization/validating-utm-tracking-in-faststore.md
Tracked in [LOC-20376](https://vtex-dev.atlassian.net/browse/LOC-20376).
[LOC-20376]: https://vtex-dev.atlassian.net/browse/LOC-20376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20376 - [LOC Review] EDU-15157: Validating UTM tracking in FastStore

docs/localization/usecart.md
Tracked in [LOC-19263](https://vtex-dev.atlassian.net/browse/LOC-19263).
[LOC-19263]: https://vtex-dev.atlassian.net/browse/LOC-19263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  LOC-19263 - EDU-13795: FastStore Cart - useCart

docs/localization/2025-06-03-vtex-shield-new-ssl-certificates-api.md
Tracked in [LOC-20507](https://vtex-dev.atlassian.net/browse/LOC-20507).
[LOC-20507]: https://vtex-dev.atlassian.net/browse/LOC-20507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20507 - add ssl certificates api release notes

docs/localization/2025-06-03-vtex-shield-new-ssl-certificates-api.md
=> add ssl certificates api release notes

docs/localization/creating-an-interface-for-your-app-settings.md
Tracked in [LOC-20362](https://vtex-dev.atlassian.net/browse/LOC-20362).
[LOC-20362]: https://vtex-dev.atlassian.net/browse/LOC-20362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20362 -  Create creating-an-interface-for-your-app-settings.md

docs/localization/do-not-remove.md_en, docs/localization/managing-secret.md
Tracked in [LOC-20366](https://vtex-dev.atlassian.net/browse/LOC-20366).
[LOC-20366]: https://vtex-dev.atlassian.net/browse/LOC-20366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LOC-20366 - EDU-15179 - [LOC] Secrets for FastStore

docs/release-notes/2025-06-24-faststore-webops-centralized-secrets-management.md
=> Updating excerpt - release note Secrets

docs/guides/Integration-Guides/erp-integration-guide/order-modifications.md
Adds table with exception errors, its codes, and descriptions. Refers to [EDU-15440](https://vtex-dev.atlassian.net/browse/EDU-15440).
[EDU-15440]: https://vtex-dev.atlassian.net/browse/EDU-15440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-15440 - Add exception codes

docs/release-notes/extensions-hub-our-new-place-to-promote-apps-and-partners-inside-vtex-admin.md
=> Remove callout from Extensions Hub RN

.github/workflows/changelog.yml
=> feat: handle release tags on changelog action

docs/release-notes/2025-07-09-new-catalog-api-endpoints-to-define-the-collection-scope-using-specifications-as-parameters.md
=> Release note new endpoints to define the collection scope using specifications as parameters

docs/faststore/components/features/my-account/overview.mdx
=> Fixing code snippet

docs/release-notes/product-variation-sorting-on-sku-selector.md
[EDU-13092](https://vtex-dev.atlassian.net/browse/EDU-13092)
[EDU-13092]: https://vtex-dev.atlassian.net/browse/EDU-13092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-13092 - Removing image

docs/guides/Search/setting-up-delivery-promise-components.md
[EDU-15772](https://vtex-dev.atlassian.net/browse/EDU-15772)
[EDU-15772]: https://vtex-dev.atlassian.net/browse/EDU-15772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update: edit delivery promise store framework guide

docs/release-notes/2025-08-06-faststore-store-coupons.md, docs/release-notes/2025-08-08-faststore-store-coupons.md
=> EDU-15601: Release note - Coupon removed from cart after validation

docs/faststore/docs/routing/managing-urls-with-redirects-and-rewrite-paths.mdx
=> (Quick win): Fix code block reference

docs/release-notes/2025-08-15-faststore-refresh-token.md
Implementation guide: https://github.com/vtexdocs/dev-portal-content/pull/2102
=> EDU-15829: FastStore refresh token (release note)

docs/faststore/components/features/delivery-promise/overview.mdx
[EDU-15907](https://vtex-dev.atlassian.net/browse/EDU-15907)
[EDU-15907]: https://vtex-dev.atlassian.net/browse/EDU-15907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EDU-15907- Delivery Promise overview

docs/guides/Search/setting-up-delivery-promise-components.md
=> update: add callout to delivery promise components guide

docs/release-notes/new-tls-security-protocol-cryptographic-cipher-suite-required-for-pci-dss-compliance-guidelines.md
PR created to update TLS version information (EDU-15983).
=> Update TLS version information

docs/faststore/components/features/delivery-promise/overview.mdx
=> Delivery Promise: Removing 'filter by shipping'

docs/faststore/docs/faststore-api/configuring-graphql-cache-control.mdx
=> EDU-15891: Add info about custom queries

docs/faststore/components/features/delivery-promise/overview.mdx
=> Delivery Promise: Updating images

docs/guides/Integration-Guides/payments-integration-guide/payments-integration-payment-provider-homologation.md
PR created to add a new section (When is payment provider homologation not required?) (EDU-15973).
=> Add new section Payment Provider Homologation guide

docs/faststore/docs/getting-started/requirements.mdx
This PR reviews the guide structure, headings, and fixes some grammar issues.
=> EDU-16036: Review FastStore requirements guide

docs/faststore/components/features/delivery-promise/components.mdx
=> Update Delivery Promise components guide

docs/faststore/components/atoms/badge.mdx
=> EDU-16042: Review Badge component guide

docs/faststore/components/molecules/search-history.mdx
=> fix(search-history.mdx): code block backtickts

docs/guides/VTEX-Platform-Overview/Composability/interactive-marchitecture-tool.md
=> Update Interactive Marchitecture tool link

docs/guides/Promotions/seller-opt-in-promotions.md
=> EDU-15167 New seller opt-in documentation

docs/guides/Promotions/seller-opt-in-promotions.md
=> EDU-15167 Added link

docs/guides/Promotions/seller-opt-in-promotions.md
=> EDU-15167 Change title

docs/guides/Pricing/contextual-price-per-shopper.md
=> EDU-14623 Updated email sharing policy
